project:
  type: book

execute:
  cache: true

book:
  title: "Foundations of Business Analytics"
  subtitle: "Crafting Narratives from Numbers"
  author: 
    - "Lachlan Deer"
    - "Patrick Ferguson"
    - "Junhao Liu"
  date: last-modified
  # cover-image: figs/fba_sticker.jpg
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - foundations/what_is_business_analytics.qmd
        - foundations/how_to_do_business_analytics.qmd
        - foundations/reproducible.qmd
    - part: "Getting Our First Insights from Data"
      chapters:
        - insights/data_visualisation.qmd
        - insights/data_manipulation.qmd
        - insights/data_tidy.qmd
    - part: "Finding and Storing Data"
      chapters:
        - data_management/data_storage.qmd
    #     - data_management/data_collection.qmd
    # - part: "Extracting Deeper Insights from Data"
    #   chapters:
    #     - advanced_analytics/data_variation.qmd
    #     - advanced_analytics/descriptive_analytics.qmd
    #     - advanced_analytics/causal_analytics.qmd
    #     - advanced_analytics/predictive_analytics.qmd
    # - part: "Ethics and Privacy"
    #   chapters:
    #     - ethics_privacy/ethics.qmd
    #     #- ethics_privacy/privacy.qmd
    # - part: "Conclusion"
    #   chapters:
    #     - conclusion/conclusion.qmd
    # - references.qmd
    - part: "Tutorials"
      number-depth: 0  # Restart numbering
      chapters:
        - tutorials/what_is_business_analytics.qmd
        - tutorials/how_to_do_business_analytics.qmd
        - tutorials/data_visualisation.qmd
        - tutorials/data_wrangling.qmd
        - tutorials/data_tidy.qmd
        - tutorials/data_storage.qmd
  # appendices:
    # - appendices/installation.qmd


bibliography: references.bib

format:
  html:
    theme:
      #- flatly
      - brand
      - unimelb.scss
    css: custom.css
    include-in-header:
      text: |
        <script src="../solution.js"></script>
  # pdf:
  #   documentclass: scrreprt
  #   include-before-body:
  #     text: |
  #       \newcommand{\solution}[1]{
  #         \begin{tcolorbox}[title=Solution]
  #           #1
  #         \end{tcolorbox}
  #       }

