<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Shaping and Combining Data for Business Analytics – Foundations of Business Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../data_management/data_storage.html" rel="next">
<link href="../insights/data_manipulation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6f77e067621728e8e5d8b75f5607b6c5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../solution.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../insights/data_visualisation.html">Getting Our First Insights from Data</a></li><li class="breadcrumb-item"><a href="../insights/data_tidy.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shaping and Combining Data for Business Analytics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundations of Business Analytics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/what_is_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Business Analytics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/how_to_do_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Core Skills of a “Business Scientist”</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/reproducible.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Workflows with R &amp; Posit Cloud</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Our First Insights from Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualisation for Business Intelligence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_manipulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Wrangling for Business Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_tidy.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shaping and Combining Data for Business Analytics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Finding and Storing Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_management/data_storage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Storing and Using Existing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_management/data_collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Collected Structured and Unstructured Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Tutorials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/what_is_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Business Analytics Skills for Inventory Management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/how_to_do_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: Core Skills of a Business Scientist &amp; Introduction to Posit Cloud</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: Data Visualisation for Business Intelligence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 4: Data Wrangling for Business Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 5: Shaping and Joining Data for Business Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_storage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 6: Storing &amp; Retrieving Data</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-business-challenge" id="toc-the-business-challenge" class="nav-link active" data-scroll-target="#the-business-challenge"><span class="header-section-number">6.1</span> The Business Challenge</a>
  <ul class="collapse">
  <li><a href="#the-topic-how-well-do-earnings-explain-what-investors-pay-for-firms" id="toc-the-topic-how-well-do-earnings-explain-what-investors-pay-for-firms" class="nav-link" data-scroll-target="#the-topic-how-well-do-earnings-explain-what-investors-pay-for-firms">The Topic: How Well Do Earnings Explain What Investors Pay for Firms?</a></li>
  </ul></li>
  <li><a href="#the-data-stock-prices-and-market-performance-from-yahoo-finance" id="toc-the-data-stock-prices-and-market-performance-from-yahoo-finance" class="nav-link" data-scroll-target="#the-data-stock-prices-and-market-performance-from-yahoo-finance">The Data: Stock Prices and Market Performance from Yahoo Finance</a>
  <ul class="collapse">
  <li><a href="#the-method-using-pivots-and-joins-to-reshape-and-combine-data" id="toc-the-method-using-pivots-and-joins-to-reshape-and-combine-data" class="nav-link" data-scroll-target="#the-method-using-pivots-and-joins-to-reshape-and-combine-data">The Method: Using Pivots and Joins to Reshape and Combine Data</a></li>
  </ul></li>
  <li><a href="#the-game-plan-what-were-aiming-for" id="toc-the-game-plan-what-were-aiming-for" class="nav-link" data-scroll-target="#the-game-plan-what-were-aiming-for"><span class="header-section-number">6.2</span> The Game Plan: What we’re aiming for</a></li>
  <li><a href="#getting-set-up-and-loading-the-data" id="toc-getting-set-up-and-loading-the-data" class="nav-link" data-scroll-target="#getting-set-up-and-loading-the-data"><span class="header-section-number">6.3</span> Getting Set Up and Loading the Data</a>
  <ul class="collapse">
  <li><a href="#r-packages-for-today" id="toc-r-packages-for-today" class="nav-link" data-scroll-target="#r-packages-for-today">R packages for today</a></li>
  <li><a href="#loading-the-financial-statements-and-price-data" id="toc-loading-the-financial-statements-and-price-data" class="nav-link" data-scroll-target="#loading-the-financial-statements-and-price-data"><span class="header-section-number">6.3.1</span> Loading the financial statements and price data</a></li>
  </ul></li>
  <li><a href="#using-pivots-to-tidy-messy-data-frames" id="toc-using-pivots-to-tidy-messy-data-frames" class="nav-link" data-scroll-target="#using-pivots-to-tidy-messy-data-frames"><span class="header-section-number">6.4</span> Using pivots to tidy messy data frames</a>
  <ul class="collapse">
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data"><span class="header-section-number">6.4.1</span> Tidy Data</a></li>
  <li><a href="#gathering-lengthening-short-data-frames" id="toc-gathering-lengthening-short-data-frames" class="nav-link" data-scroll-target="#gathering-lengthening-short-data-frames"><span class="header-section-number">6.4.2</span> ‘Gathering’: Lengthening short data frames</a></li>
  <li><a href="#spreading-widening-narrow-data-frames" id="toc-spreading-widening-narrow-data-frames" class="nav-link" data-scroll-target="#spreading-widening-narrow-data-frames"><span class="header-section-number">6.4.3</span> ‘Spreading’: Widening narrow data frames</a></li>
  </ul></li>
  <li><a href="#using-joins-to-make-one-data-frame-from-many" id="toc-using-joins-to-make-one-data-frame-from-many" class="nav-link" data-scroll-target="#using-joins-to-make-one-data-frame-from-many"><span class="header-section-number">6.5</span> Using joins to make one data frame from many</a>
  <ul class="collapse">
  <li><a href="#understanding-how-keys-connect-data-frames" id="toc-understanding-how-keys-connect-data-frames" class="nav-link" data-scroll-target="#understanding-how-keys-connect-data-frames"><span class="header-section-number">6.5.1</span> Understanding how keys connect data frames</a></li>
  <li><a href="#combining-variables-from-two-data-frames-with-mutating-joins" id="toc-combining-variables-from-two-data-frames-with-mutating-joins" class="nav-link" data-scroll-target="#combining-variables-from-two-data-frames-with-mutating-joins"><span class="header-section-number">6.5.2</span> Combining variables from two data frames with mutating joins</a></li>
  <li><a href="#selecting-rows-from-a-data-frame-with-filtering-joins" id="toc-selecting-rows-from-a-data-frame-with-filtering-joins" class="nav-link" data-scroll-target="#selecting-rows-from-a-data-frame-with-filtering-joins"><span class="header-section-number">6.5.3</span> Selecting rows from a data frame with filtering joins</a></li>
  </ul></li>
  <li><a href="#bringing-it-all-together-reshaping-and-combining-data" id="toc-bringing-it-all-together-reshaping-and-combining-data" class="nav-link" data-scroll-target="#bringing-it-all-together-reshaping-and-combining-data"><span class="header-section-number">6.6</span> Bringing it all together: Reshaping and Combining Data</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">6.7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../insights/data_visualisation.html">Getting Our First Insights from Data</a></li><li class="breadcrumb-item"><a href="../insights/data_tidy.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shaping and Combining Data for Business Analytics</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shaping and Combining Data for Business Analytics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learning Goals
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this lecture, you should be able to:</p>
<ul>
<li>Distinguish between tidy and messy data structures, and explain why tidy data makes manipulation and analysis more efficient.<br>
</li>
<li>Use <code>pivot_longer()</code> to tidy “short and wide” data sets by stacking year or variable columns into a single long format.<br>
</li>
<li>Use <code>pivot_wider()</code> to tidy “long and narrow” data sets by spreading variable names stored in rows into their own columns.<br>
</li>
<li>Use mutating joins (<code>left_join()</code>, <code>right_join()</code>, <code>full_join()</code>, <code>inner_join()</code>) to combine data sets by adding columns from one table to another.<br>
</li>
<li>Use filtering joins (<code>semi_join()</code>, <code>anti_join()</code>) to identify overlap or gaps between data sets, and to detect implicit missing observations.<br>
</li>
<li>Explain the role of primary keys and foreign keys in linking data frames, including the use of compound keys.<br>
</li>
<li>Evaluate how different join types affect the number of rows and the presence of missing values in the resulting data set.<br>
</li>
</ul>
</div>
</div>
<section id="the-business-challenge" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="the-business-challenge"><span class="header-section-number">6.1</span> The Business Challenge</h2>
<section id="the-topic-how-well-do-earnings-explain-what-investors-pay-for-firms" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-topic-how-well-do-earnings-explain-what-investors-pay-for-firms">The Topic: How Well Do Earnings Explain What Investors Pay for Firms?</h3>
<p>When investors buy shares, they are not just purchasing a slice of today’s profits — they are buying into expectations of future earnings. A company’s reported earnings per share (EPS) and the multiple of those earnings that investors are willing to pay, the price-to-earnings (P/E) ratio, are two of the most widely used measures in equity markets. Together, they capture the link between operating performance and market valuation.</p>
<p>Yet these measures are rarely straightforward to analyze. Financial data is often recorded in messy, inconsistent formats, and the information we need is usually spread across multiple data sets. To understand how investors value Australian firms, we need to tidy and combine stock price data, earnings data, and industry classifications into a single, coherent data set.</p>
<p>The business questions we focus on are: <strong>How closely do earnings per share align with stock prices? How do P/E ratios differ across industries? What patterns emerge when we track these measures over time?</strong></p>
<p>By reshaping messy data sets with pivots and merging them with joins, we can create a tidy, integrated data set that allows us to explore how investors interpret earnings and how valuations vary across the Australian economy.</p>
</section>
</section>
<section id="the-data-stock-prices-and-market-performance-from-yahoo-finance" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="the-data-stock-prices-and-market-performance-from-yahoo-finance">The Data: Stock Prices and Market Performance from Yahoo Finance</h2>
<p>To answer the questions in this chapter, we draw on firm-year ASX stock price data from Yahoo Finance. We will also examine the ASX financial statements data set that we explored in last week’s lecture and tutorial. Unlike this data set, the ASX stock price data set that we introduce this week captures market-based measures of firm performance over <em>multiple years</em> (i.e., not just 2024).</p>
<p>Stock prices in our data set are recorded as the closing price at the end of each firm’s fiscal year. This allows us to align market performance with the accounting data reported in annual financial statements. Our data set contains the following variables:</p>
<ul>
<li>Company name (<code>conm</code>) – the firm’s name as listed on the ASX<br>
</li>
<li>Firm identifier (<code>gvkey</code>) – a unique numeric code that tracks companies over time<br>
</li>
<li>Fiscal year (<code>fyear</code>) – the accounting year associated with the stock price and earnings</li>
</ul>
<p>In addition to raw prices, our data set also contains two derived financial measures that are widely applied by analysts and investors:</p>
<ul>
<li>Stock price (<code>price</code>) – the firm’s share price at fiscal year-end, measured in Australian dollars<br>
</li>
<li>Earnings per share (<code>eps</code>) – net earnings available to common shareholders divided by the number of shares outstanding:<br>
<span class="math display">\[
EPS = \frac{\text{Earnings}}{\text{Shares Outstanding}}
\]</span><br>
</li>
<li>Price-to-earnings ratio (<code>pe</code>) – the ratio of the firm’s stock price to its earnings per share:<br>
<span class="math display">\[
P/E = \frac{\text{Price}}{EPS}
\]</span></li>
</ul>
<p>These variables allow us to link operating performance with market performance, and to investigate the relationship between what firms earn and what investors are willing to pay. By working with these data, we can replicate the kinds of comparisons analysts use to value companies and industries.</p>
<section id="the-method-using-pivots-and-joins-to-reshape-and-combine-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-method-using-pivots-and-joins-to-reshape-and-combine-data">The Method: Using Pivots and Joins to Reshape and Combine Data</h3>
<blockquote class="blockquote">
<p>“Data that is loved tends to survive.” — Kurt Bollacker (computer scientist and digital archivist)</p>
</blockquote>
<p>While tidy data makes analysis straightforward, most real-world data arrives messy, spread across multiple files, or structured in ways that do not align with analytical needs. To work effectively, we need tools that can both reshape individual datasets and combine information across multiple sources.</p>
<p>In R, the <code>tidyr</code> package provides functions for reshaping data:</p>
<ul>
<li><code>pivot_longer()</code> to lengthen “short and wide” datasets by stacking values into a single column,<br>
</li>
<li><code>pivot_wider()</code> to shorten “long and narrow” datasets by spreading values into multiple columns.</li>
</ul>
<p>These pivots allow us to convert messy structures into tidy data, where variables are columns, observations are rows, and values are cells.</p>
<p>The <code>dplyr</code> package complements this by providing join functions that merge datasets:</p>
<ul>
<li>Mutating joins (<code>left_join()</code>, <code>right_join()</code>, <code>inner_join()</code>, <code>full_join()</code>) add variables from one table to another,<br>
</li>
<li>Filtering joins (<code>semi_join()</code>, <code>anti_join()</code>) filter observations based on whether they appear in another table.</li>
</ul>
<p>All joins rely on keys — primary keys that uniquely identify observations in one dataset, and foreign keys that reference those identifiers in another. Understanding and using keys correctly is critical for combining information without introducing errors or duplicates.</p>
<p>Together, pivots and joins form the backbone of data wrangling workflows. They allow us to take messy, fragmented business data — such as financial statements, stock prices, and industry classifications — and transform it into a single tidy data set that supports reliable analysis, clear visualization, and sound decision-making.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Beyond R">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beyond R
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pivoting and joining are not unique to R. The same concepts appear in other tools:<br>
- SQL provides <code>PIVOT</code>/<code>UNPIVOT</code> clauses and join operations,<br>
- Excel offers PivotTables and lookup functions,<br>
- Python (pandas) implements <code>.pivot()</code>, <code>.melt()</code>, and <code>.merge()</code>.</p>
<p>Mastering these techniques in R builds transferable skills that apply across the full range of data analysis environments.</p>
</div>
</div>
</section>
</section>
<section id="the-game-plan-what-were-aiming-for" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-game-plan-what-were-aiming-for"><span class="header-section-number">6.2</span> The Game Plan: What we’re aiming for</h2>
<p>Recall our workflow:</p>
<ol type="1">
<li>Define the Business Question(s) &amp; Plan Outputs<br>
</li>
<li><strong>Acquire and Prepare Data</strong><br>
</li>
<li>Explore and Visualize Patterns<br>
</li>
<li>Analyze and Interpret Findings<br>
</li>
<li>Communicate Insights and Recommendations</li>
</ol>
<p>Sketch of the plan:</p>
<ul class="task-list">
<li><label><input type="checkbox">Define the Business Questions: How do earnings explain stock prices? How do P/E ratios vary across industries and over time?<br>
</label></li>
<li><label><input type="checkbox">Load stock price, earnings, and sub-industry lookup data from Yahoo Finance<br>
</label></li>
<li><label><input type="checkbox">Wrangle data by reshaping with <code>pivot_longer()</code> and <code>pivot_wider()</code> to ensure tidy structure<br>
</label></li>
<li><label><input type="checkbox">Combine data frames using joins (<code>left_join()</code>, <code>inner_join()</code>, <code>anti_join()</code>) to link financials, stock prices, and industry codes<br>
</label></li>
<li><label><input type="checkbox">Diagnose missing values (explicit and implicit) and assess data coverage<br>
</label></li>
<li><label><input type="checkbox">Visualize P/E ratios and price–earnings patterns across firms, years, and industries (we will tackle in the tutorial)</label></li>
<li><label><input type="checkbox">Interpret what these patterns reveal about firm performance and investor expectations (we will tackle in the tutorial)</label></li>
</ul>
<hr>
<p>Let’s get started!</p>
</section>
<section id="getting-set-up-and-loading-the-data" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="getting-set-up-and-loading-the-data"><span class="header-section-number">6.3</span> Getting Set Up and Loading the Data</h2>
<section id="r-packages-for-today" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="r-packages-for-today">R packages for today</h3>
<p>Much of this week’s material will involve our using the <code>tidyr</code> and <code>dplyr</code> packages, which are core parts of the <code>tidyverse.</code> These two packages work seamlessly together, as well as with others such as <code>ggplot2</code> and <code>stringr</code>, making them essential tools for data wrangling and visualization.</p>
<p>And so to begin, we need to load these packages and others that we will use for this chapter.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the tidyverse for data manipulation and visualization</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load scales for axis formatting and transformations</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load ggokabeito for a colour-blind-friendly palette (available if you choose to use it)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggokabeito)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Load ggthemes for additional polished ggplot themes</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Load patchwork to combine multiple ggplots into one figure</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Load stringr for consistent string manipulation helpers</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="What is `scales`?">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is <code>scales</code>?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You may notice that we continue to use many of the visualization tools introduced earlier in the course. One additional package that appears this week is <code>scales</code>. This package provides a consistent set of functions for formatting numbers, dates, and other values in plots. For example, it can transform raw dollar amounts into currency labels, percentages into readable strings, or continuous variables into log-scaled axes.</p>
<p>In this week’s lecture and tutorial, we will use <code>scales</code> to format axes and labels in our plots, ensuring that visualizations are clear, professional, and easy to interpret.</p>
<p>Some examples include:<br>
- <code>label_percent()</code> – convert proportions like <code>0.25</code> into <code>"25%"</code><br>
- <code>label_dollar()</code> – format numbers like <code>1000000</code> into <code>"$1,000,000"</code><br>
- <code>label_comma()</code> – add thousands separators for readability (e.g., <code>10000</code> → <code>"10,000"</code>)<br>
- <code>label_date()</code> – format dates consistently for time series plots</p>
<p>These functions help ensure our plots communicate results in a way that is accessible and professional.</p>
</div>
</div>
</div>
</section>
<section id="loading-the-financial-statements-and-price-data" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="loading-the-financial-statements-and-price-data"><span class="header-section-number">6.3.1</span> Loading the financial statements and price data</h3>
<p>We now import the data sets that we will use in this week’s lecture. The first is the ASX financial statements data set we examined last week, which should be familiar to you by now:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the 2024 ASX 200 data set</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>asx_200_2024 <span class="ot">&lt;-</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(<span class="st">"data/asx_200_2024.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Code our new variable fyear as a character type for subsequent joins</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">fyear =</span> <span class="fu">as.character</span>(fyear)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also import a ‘messy’ snapshot of this data set, which we will tidy as part of this module:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the wide version of the 2024 ASX 200 data set</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>financials_messy <span class="ot">&lt;-</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(<span class="st">"data/financials_messy.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We next import the ASX price data in two forms, a ‘wide’ snapshot and a ‘messy’ snapshot, both of which we will tidy as part of this module:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the wide version of the ASX price data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>prices_wide <span class="ot">&lt;-</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(<span class="st">"data/prices_wide.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the messy version of the ASX price data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>prices_messy <span class="ot">&lt;-</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">read_csv</span>(<span class="st">"data/prices_messy.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we import a look-up table that links industry codes to industry names. We will use this identify each firm’s industry in our sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the GICS industry look-up file</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>gics_industry <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/GICS_industry.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="using-pivots-to-tidy-messy-data-frames" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="using-pivots-to-tidy-messy-data-frames"><span class="header-section-number">6.4</span> Using pivots to tidy messy data frames</h2>
<section id="tidy-data" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="tidy-data"><span class="header-section-number">6.4.1</span> Tidy Data</h3>
<div class="callout callout-style-default callout-important callout-titled" title="What is Tidy Data?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is Tidy Data?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A tidy data set has the following properties:</p>
<ul>
<li>Each variable is a column; each column is a variable.<br>
</li>
<li>Each observation is a row; each row is an observation.<br>
</li>
<li>Each value is a cell; each cell is a single value.<br>
</li>
</ul>
</div>
</div>
<p>We can see that our ASX financial statements data set, the one we examined in the last module, is tidy. Here’s a snapshot of a few rows and columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select a few key variables: company name, year, EBIT, and industry</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(conm, fyear, ebit, industry) <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Preview the first 10 rows of the data</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   conm                   fyear   ebit industry                                 
   &lt;chr&gt;                  &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;                                    
 1 BHP GROUP LTD          2024  22771  Metals &amp; Mining                          
 2 TELSTRA GROUP LIMITED  2024   3712  Diversified Telecommunication Services   
 3 CSL LTD                2024   3896  Biotechnology                            
 4 TRANSURBAN GROUP       2024   1132  Transportation Infrastructure            
 5 WOOLWORTHS GROUP LTD   2024   3100  Consumer Staples Distribution &amp; Retail (…
 6 FORTESCUE LTD          2024   8520  Metals &amp; Mining                          
 7 WESFARMERS LTD         2024   3849  Broadline Retail (New Name)              
 8 RAMSAY HEALTH CARE LTD 2024    939. Health Care Providers &amp; Services         
 9 QANTAS AIRWAYS LTD     2024   2198  Passenger Airlines (New name)            
10 ORIGIN ENERGY LTD      2024    952  Electric Utilities                       </code></pre>
</div>
</div>
<p>Each variable is a column; each column is a variable (e.g., firm name, year, EBIT, etc). Each observation is a row; each row is an observation (e.g., BHP’s financials in 2024, etc). And, each value is a cell; each cell is a single value (BHP’s EBIT in 2024 was $22,771 million).</p>
<p>Storing data using this tidy structure makes it easier to manipulate and examine the data because it has an underlying uniformity. Such a structure also takes advantage of R’s vectorized nature - i.e., most R functions work with vectors of values (e.g., columns and rows). In fact, <code>dplyr</code>, <code>ggplot</code>, and all the packages in the <code>tidyverse</code> are explicitly designed to work with tidy data (hence the name…).</p>
<p>Unfortunately, however, most real data is untidy (often because people who collect and store data are not the ones who analyse and use the data for decision making). And so, we often need to tidy a data set before we can start using the data to answer empirical questions and solve business problems.</p>
<p>Pivoting is the primary tool that we will use for tidying messy data. Pivoting allows you to change the form of your data without changing any of its values-you pivot your data so that variables are structured as columns, and observations as rows.</p>
<div class="callout callout-style-default callout-important callout-titled" title="What are Pivots?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What are Pivots?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A pivot reshapes data by turning rows into columns or columns into rows, depending on the question you want to answer.</p>
<p>In R, we use the tidyr functions:</p>
<ul>
<li><code>pivot_longer()</code> – stack columns into rows (e.g., years across columns → one “year” column).<br>
</li>
<li><code>pivot_wider()</code> – spread rows into columns (e.g., turn a key-value pair into new columns).</li>
</ul>
<p>The same concept exists in other tools:</p>
<ul>
<li>SQL: <code>PIVOT</code> and <code>UNPIVOT</code> clauses reshape data in queries.<br>
</li>
<li>Excel: PivotTables reorganize and summarize data.<br>
</li>
<li>Python (pandas): <code>.pivot()</code>, <code>.pivot_table()</code>, and <code>.melt()</code> work like R’s pivots.</li>
</ul>
<p>Applications include converting messy wide data into tidy long form for analysis, or producing summary tables by category and time.</p>
<p>In short, pivoting is a universal wrangling skill: learning it in R helps you apply it in SQL, Excel, and beyond.</p>
</div>
</div>
</section>
<section id="gathering-lengthening-short-data-frames" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="gathering-lengthening-short-data-frames"><span class="header-section-number">6.4.2</span> ‘Gathering’: Lengthening short data frames</h3>
<p>In practice, we often need to work with data that is ‘short and wide’-i.e., where observations are stretched across rather than down columns. To tidy such data, we can use <code>pivot_longer()</code>, which folds observations down columns.</p>
<p>If we open and examine our ‘wide’ ASX price data, we can see that this data set is short and wide:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>prices_wide <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   gvkey  conm                         `2021`  `2022`  `2023`  `2024`
   &lt;chr&gt;  &lt;chr&gt;                         &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 005302 LABYRINTH RESOURCES LIMITED   0.034   0.02    0.006   0.017
 2 013312 BHP GROUP LTD                37.6    38.5    44.2    46.0  
 3 014242 ANSELL LTD                   34.2    25.2    22.1    31.8  
 4 016602 THE IQ GROUP GLOBAL LTD       0.2    NA      NA      NA    
 5 017525 ORIGIN ENERGY LTD             4.73    5.17    8.78   10.0  
 6 018043 NEWS CORP                    23.5    15.1    20.1    26.6  
 7 019731 ORBITAL CORP LTD              0.65    0.215   0.16    0.079
 8 023681 SENEX ENERGY LTD              3.69   NA      NA      NA    
 9 024433 ASTUTE METALS NL              0.004   0.004   0.037   0.027
10 031887 RESMED INC                  264.    218.    148.    244.   </code></pre>
</div>
</div>
<p>Instead of structuring each firm-year observation as a row, this data set stretches firm-year observations across the data frame, so that each row is a firm and the columns store the corresponding values for that year (e.g., BHP’s closing stock price at fiscal year-end in 2021, in 2022, etc).</p>
<p>An issue with this data structure is that we have data in the column names (i.e., the year of the observation), rather than in the cells. To more easily apply the tidyverse functions to this data and so better facilitate analyses, we need to lengthen and narrow this data frame so that we store all the data in our data frame in cells rather than column names (i.e., we have a column for identifying the year of observation and a single column for stock price, and so that the cells under each column contain data, and no data is contained in the column names themselves).</p>
<p>We can use <code>pivot_longer()</code> function to lengthen and narrow our stock price data in this manner:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="ot">&lt;-</span> prices_wide <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select the year columns we want to reshape from wide to long</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"2021"</span>, <span class="st">"2022"</span>, <span class="st">"2023"</span>, <span class="st">"2024"</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Name of the new column that will store the former column names (years)</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"fyear"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Name of the new column that will store the values (prices)</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"price"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first 10 rows of the reshaped (tidy) data</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   gvkey  conm                        fyear  price
   &lt;chr&gt;  &lt;chr&gt;                       &lt;chr&gt;  &lt;dbl&gt;
 1 005302 LABYRINTH RESOURCES LIMITED 2021   0.034
 2 005302 LABYRINTH RESOURCES LIMITED 2022   0.02 
 3 005302 LABYRINTH RESOURCES LIMITED 2023   0.006
 4 005302 LABYRINTH RESOURCES LIMITED 2024   0.017
 5 013312 BHP GROUP LTD               2021  37.6  
 6 013312 BHP GROUP LTD               2022  38.5  
 7 013312 BHP GROUP LTD               2023  44.2  
 8 013312 BHP GROUP LTD               2024  46.0  
 9 014242 ANSELL LTD                  2021  34.2  
10 014242 ANSELL LTD                  2022  25.2  </code></pre>
</div>
</div>
<p>Great. Our ASX price data is now tidy - each column is a variable (e.g., price), each row an observation (e.g., BHP’s stock price in 2021), and each cell a value (e.g., BHP’s closing stock price at year-end 2021 is $37.61).</p>
<div class="exercise">
<div class="exercise-time">
<p>10 min</p>
</div>
<p>You’re given a messy ASX prices data frame, <code>prices_messy</code>, where firm-year information is spread across columns (e.g., <code>price_2023</code>, <code>eps_2024</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>prices_messy <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   gvkey  conm                      price_2023 price_2024 eps_2023 eps_2024
   &lt;chr&gt;  &lt;chr&gt;                          &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 327267 1414 DEGREES LTD               0.04       0.067  -0.0091  -0.0107
 2 349318 29METALS LIMITED               0.375     NA      -0.799   NA     
 3 284698 3D ENERGI LIMITED              0.056      0.07    0.0129  -0.0075
 4 317959 3P LEARNING LTD                1.27       1.02    0.023   -0.208 
 5 339106 4DMEDICAL LTD                  0.45       0.675  -0.105   -0.0971
 6 314650 4DS MEMORY LTD                 0.135      0.084  -0.0038  -0.0031
 7 324960 5E ADVANCED MATERIALS INC      2.26       0.54   -0.7     -1.18  
 8 325746 5G NETWORKS LIMITED            0.125      0.148  -0.0579  -0.0836
 9 253429 88 ENERGY LTD                  0.005     NA      -0.0006  NA     
10 323980 8COMMON LTD                    0.075      0.041  -0.0147  -0.0114</code></pre>
</div>
</div>
<p>Your goal is to lengthen and narrow this data so that:</p>
<ul>
<li>Each row is a firm–year observation.<br>
</li>
<li>Column names are variables (e.g., <code>price</code>, <code>eps</code>, <code>year</code>), and no data is stored in column names.<br>
</li>
<li>Missing year-specific values are dropped.</li>
</ul>
<p>Using <code>pivot_longer()</code>, reshape <code>prices_messy</code> into a tidy data frame named <code>prices_tidier</code> with columns: <code>gvkey</code>, <code>conm</code>, <code>year</code>, <code>price</code>, and <code>eps</code>.</p>
<p>Finally, show the first 10 rows.</p>
</div>
<div class="solution-header">
<p>Solution</p>
</div>
<div class="solution-content">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy the wide, mixed-name columns (e.g., price_2023, eps_2024) into long form</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>prices_tidier <span class="ot">&lt;-</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  prices_messy <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select all columns that start with "price" or "eps"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(dplyr<span class="sc">::</span><span class="fu">starts_with</span>(<span class="st">"price"</span>), dplyr<span class="sc">::</span><span class="fu">starts_with</span>(<span class="st">"eps"</span>)),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Split column names into two parts:</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#  - ".value" maps to new column names (price, eps)</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#  - "year" captures the year suffix</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to   =</span> <span class="fu">c</span>(<span class="st">".value"</span>, <span class="st">"year"</span>),</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_sep  =</span> <span class="st">"_"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Drop rows where either price or eps is missing</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_drop_na =</span> <span class="cn">TRUE</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">as.integer</span>(year))</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first 10 rows</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>prices_tidier <span class="sc">|&gt;</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   gvkey  conm               year price     eps
   &lt;chr&gt;  &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1 327267 1414 DEGREES LTD   2023 0.04  -0.0091
 2 327267 1414 DEGREES LTD   2024 0.067 -0.0107
 3 349318 29METALS LIMITED   2023 0.375 -0.799 
 4 284698 3D ENERGI LIMITED  2023 0.056  0.0129
 5 284698 3D ENERGI LIMITED  2024 0.07  -0.0075
 6 317959 3P LEARNING LTD    2023 1.27   0.023 
 7 317959 3P LEARNING LTD    2024 1.02  -0.208 
 8 339106 4DMEDICAL LTD      2023 0.45  -0.105 
 9 339106 4DMEDICAL LTD      2024 0.675 -0.0971
10 314650 4DS MEMORY LTD     2023 0.135 -0.0038</code></pre>
</div>
</div>
</div>
</section>
<section id="spreading-widening-narrow-data-frames" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="spreading-widening-narrow-data-frames"><span class="header-section-number">6.4.3</span> ‘Spreading’: Widening narrow data frames</h3>
<p>Messy data can also occur in practice in the form of data frames that store individual observations across multiple rows. In order to tidy these, we use <code>pivot_wider()</code> to collapse multiple rows into a single row that stretches across additional columns (i.e., we take our messy data frame that is too ‘long’ and too ‘narrow’ and ‘shorten’ and ‘widen’ to tidy it).</p>
<p>Let’s move away from our ASX price data back to our financial statements data. The following is a messy snapshot of our ASX financial statements data, messy in the sense that it is too long and narrow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>financials_messy <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   gvkey  conm                  fyear measure_name measure_value
   &lt;chr&gt;  &lt;chr&gt;                 &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt;
 1 013312 BHP GROUP LTD          2024 at                  102362
 2 013312 BHP GROUP LTD          2024 sale                 55658
 3 013312 BHP GROUP LTD          2024 ebit                 22771
 4 210216 TELSTRA GROUP LIMITED  2024 at                   45550
 5 210216 TELSTRA GROUP LIMITED  2024 sale                 22928
 6 210216 TELSTRA GROUP LIMITED  2024 ebit                  3712
 7 223003 CSL LTD                2024 at                   38022
 8 223003 CSL LTD                2024 sale                 14690
 9 223003 CSL LTD                2024 ebit                  3896
10 212650 TRANSURBAN GROUP       2024 at                   36694</code></pre>
</div>
</div>
<p>Immediately, we can see that we have firm-year observations showing up across multiple rows (e.g., BHP in 2024 is represented three times, one for each financial measure). We can also see that we have variable names as values in a single column (i.e., the column <code>measure_name</code> stores the variables names <code>at</code>, <code>sales</code>, and <code>ebit</code>.</p>
<p>As we explain above, to tidy this data frame, we need to collapse our firm-year observations into a single row, and then widen our data frame so that the variables stored in the column ‘measure_name’ each become their own columns. These new columns can then store the values that these measures take.</p>
<p>We use <code>pivot_wider()</code> to transform our data frame’s structure in this manner. As we see in the code below, <code>pivot_wider()</code> uses the argument <code>names_from</code> to take the new column names from the pre-existing <code>measure_name</code> column, and then uses the <code>values_from</code> argument to take the values for each observation for these new columns from the pre-existing <code>measure_value</code> column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>financials_tidy <span class="ot">&lt;-</span> financials_messy <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Column names will be taken from the values in 'measure_name'</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> measure_name,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Cell values will be filled from 'measure_value'</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> measure_value</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first 10 rows of the tidied financials</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>financials_tidy <span class="sc">|&gt;</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
   gvkey  conm                   fyear     at   sale   ebit
   &lt;chr&gt;  &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 013312 BHP GROUP LTD           2024 102362 55658  22771 
 2 210216 TELSTRA GROUP LIMITED   2024  45550 22928   3712 
 3 223003 CSL LTD                 2024  38022 14690   3896 
 4 212650 TRANSURBAN GROUP        2024  36694  4119   1132 
 5 100894 WOOLWORTHS GROUP LTD    2024  33936 67922   3100 
 6 212427 FORTESCUE LTD           2024  30060 18220   8520 
 7 101601 WESFARMERS LTD          2024  27309 44189   3849 
 8 226744 RAMSAY HEALTH CARE LTD  2024  20894 16660.   939.
 9 220244 QANTAS AIRWAYS LTD      2024  20564 20114   2198 
10 017525 ORIGIN ENERGY LTD       2024  20454 16138    952 </code></pre>
</div>
</div>
<p>Great. Look at BHP: the mining company is now represented as a single row, and we have columns for assets, sales, and ebit that store BHP’s values for those financial measures in 2024. As such, we can see that we have successfully shortened and widened our financial statements data frame-i.e., each firm-year observation shows up as a single row in our data frame, and each financial measure is stored in its own column and each of these columns takes this measure’s value for a given firm-year observation.</p>
<p>In summary, we have used two core <code>tidyr</code> functions, <code>pivot_longer()</code> and <code>pivot_wider()</code>-to tidy messy data sets and so ensure that our data has variables in columns and observations in rows (and so values in cells). While tidying data in this manner may not seem especially interesting or exciting, it is hugely important because tidy data makes cleaning, combining, and analysing data to extract insights much more efficient, straight forward, and robust.</p>
</section>
</section>
<section id="using-joins-to-make-one-data-frame-from-many" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="using-joins-to-make-one-data-frame-from-many"><span class="header-section-number">6.5</span> Using joins to make one data frame from many</h2>
<p>So far we have been working with individual data frames, but in practice single data frames rarely contain all the information necessary for the analyses that we would like to conduct in order to answer important, interesting and timely business questions. Instead, we commonly need to use multiple data frames to answer these questions, and so we must join these data frames together before we can manipulate and analyze their (combined) contents.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Mutating vs Filtering Joins">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mutating vs Filtering Joins
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the remainder of this module, we will introduce and explore two important types of joins:</p>
<ul>
<li>Mutating joins add new variables to one data frame from matching observations in another.<br>
</li>
<li>Filtering joins filter observations from one data frame based on whether or not they match an observation in another.</li>
</ul>
<p>The former adds columns, while the latter removes rows.</p>
<p>Joins use a pair of keys—a primary key and a foreign key—to combine tables.<br>
A primary key is a variable (or set of variables) that uniquely identifies each observation, while a foreign key links back to that identifier in another data frame.</p>
<p>Before we can understand and employ joins, we need to understand how keys connect data frames.</p>
</div>
</div>
<section id="understanding-how-keys-connect-data-frames" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="understanding-how-keys-connect-data-frames"><span class="header-section-number">6.5.1</span> Understanding how keys connect data frames</h3>
<p>Let’s grab a snapshot of the now familiar data frame that contains financials for the 200-largest firms in the ASX in 2024. In this data, the <strong>primary key</strong> is the <code>gvkey</code>, a six-digit code that uniquely identifies each firm in the data frame (note, <code>gvkey</code> in our data is a character type, not a numeric type).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only the key identifiers and industry columns from the ASX 200 financials</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>firms <span class="ot">&lt;-</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gvkey, conm, fyear, gind)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the first 10 rows of the reduced firms data frame</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>firms <span class="sc">|&gt;</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   gvkey  conm                   fyear   gind
   &lt;chr&gt;  &lt;chr&gt;                  &lt;chr&gt;  &lt;dbl&gt;
 1 013312 BHP GROUP LTD          2024  151040
 2 210216 TELSTRA GROUP LIMITED  2024  501010
 3 223003 CSL LTD                2024  352010
 4 212650 TRANSURBAN GROUP       2024  203050
 5 100894 WOOLWORTHS GROUP LTD   2024  301010
 6 212427 FORTESCUE LTD          2024  151040
 7 101601 WESFARMERS LTD         2024  255030
 8 226744 RAMSAY HEALTH CARE LTD 2024  351020
 9 220244 QANTAS AIRWAYS LTD     2024  203020
10 017525 ORIGIN ENERGY LTD      2024  551010</code></pre>
</div>
</div>
<p>Now, let’s compare the above to <code>gics_industry</code>, a look-up table of six-digit industry codes, <code>gind</code>, each of which uniquely identifies an industry in the economy. This six-digit code, <code>gind</code>, is the primary key for our industry look-up table:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>gics_industry <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
     gind industry                   
    &lt;dbl&gt; &lt;chr&gt;                      
 1 101010 Energy Equipment &amp; Services
 2 101020 Oil, Gas &amp; Consumable Fuels
 3 151010 Chemicals                  
 4 151020 Construction Materials     
 5 151030 Containers &amp; Packaging     
 6 151040 Metals &amp; Mining            
 7 151050 Paper &amp; Forest Products    
 8 201010 Aerospace &amp; Defense        
 9 201020 Building Products          
10 201030 Construction &amp; Engineering </code></pre>
</div>
</div>
<p>As we defined it above, a <strong>foreign key</strong> is a variable (or set of variables) that corresponds to a <strong>primary key</strong> in another table or data frame. Staying with our examples above, <code>gind</code> is the foreign key for <code>firms</code> in that it corresponds to <code>gind</code>, the primary key of <code>gics_industry</code>.</p>
<p>Before using our primary and foreign keys to join tables, we first should verify that our primary keys uniquely identify observations in their associated data frames:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many times each gvkey appears in firms</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>firms <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gvkey) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Keep only gvkeys that appear more than once</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: gvkey &lt;chr&gt;, n &lt;int&gt;</code></pre>
</div>
</div>
<p>And, for our gics industry data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many times each gind appears in gics_industry</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>gics_industry <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gind) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Keep only ginds that appear more than once</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: gind &lt;dbl&gt;, n &lt;int&gt;</code></pre>
</div>
</div>
<p>Great. We have confirmed that our primary keys uniquely identify each observation in these data frames. It is worth noting here that while <code>gind</code> is the primary key for <code>gics_industry</code> (and so uniquely identifies observations in this data frame), it does not uniquely identify observations in <code>firms</code>, where (as we mentioned above) <code>gind</code> serves as the foreign key. We can easily show this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of times each gind appears in firms</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>firms <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gind) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Arrange in descending order to check whether gind uniquely identifies observations</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 46 × 2
     gind     n
    &lt;dbl&gt; &lt;int&gt;
 1 151040    42
 2 255040    14
 3 201030    11
 4 253010    11
 5 101020     9
 6 202010     7
 7 302020     7
 8 351020     7
 9 201070     5
10 151010     4
# ℹ 36 more rows</code></pre>
</div>
</div>
<div class="exercise">
<div class="exercise-time">
<p>2 min</p>
</div>
<p>Before using our keys to join data sets, confirm there are no missing values in the primary key columns. Otherwise, those observations can’t be identified. Do so for <code>gvkey</code> in <code>firms</code> and for <code>gind</code> in <code>gics_industry</code>.</p>
</div>
<div class="solution-header">
<p>Solution</p>
</div>
<div class="solution-content">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether any observations in firms have a missing gvkey (should be none)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>firms <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="fu">is.na</span>(gvkey))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: gvkey &lt;chr&gt;, conm &lt;chr&gt;, fyear &lt;chr&gt;, gind &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether any observations in gics_industry have a missing gind (should be none)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>gics_industry <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="fu">is.na</span>(gind))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 2
# ℹ 2 variables: gind &lt;dbl&gt;, industry &lt;chr&gt;</code></pre>
</div>
</div>
</div>
</section>
<section id="combining-variables-from-two-data-frames-with-mutating-joins" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="combining-variables-from-two-data-frames-with-mutating-joins"><span class="header-section-number">6.5.2</span> Combining variables from two data frames with mutating joins</h3>
<div class="callout callout-style-default callout-important callout-titled" title="Mutating Joins: The `left_join()`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mutating Joins: The <code>left_join()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>In <code>dplyr</code>, join functions share a common interface: they take a pair of data frames <code>(x, y)</code> and return a data frame.</p>
<p>We begin with <code>left_join()</code>, a mutating join that combines variables from two data frames.</p>
<ul>
<li>Mutating joins first match observations by keys, then copy columns from one table to the other.<br>
</li>
<li><code>left_join(x, y, by = ...)</code> adds columns from <code>y</code> to <code>x</code> and guarantees the output has the same number of rows as <code>x</code> (the “left” table).</li>
</ul>
</div>
</div>
<p>Let’s return to our examples from above, and see how we can use <code>left_join()</code> to add a column that identifies the industry in which each firm operates in our firm names data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the firms data with the GICS industry lookup table</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Match on gind (the foreign key in firms, primary key in gics_industry)</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>firms <span class="sc">|&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    gics_industry, </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gind)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 5
   gvkey  conm                   fyear   gind industry                          
   &lt;chr&gt;  &lt;chr&gt;                  &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;                             
 1 013312 BHP GROUP LTD          2024  151040 Metals &amp; Mining                   
 2 210216 TELSTRA GROUP LIMITED  2024  501010 Diversified Telecommunication Ser…
 3 223003 CSL LTD                2024  352010 Biotechnology                     
 4 212650 TRANSURBAN GROUP       2024  203050 Transportation Infrastructure     
 5 100894 WOOLWORTHS GROUP LTD   2024  301010 Consumer Staples Distribution &amp; R…
 6 212427 FORTESCUE LTD          2024  151040 Metals &amp; Mining                   
 7 101601 WESFARMERS LTD         2024  255030 Broadline Retail (New Name)       
 8 226744 RAMSAY HEALTH CARE LTD 2024  351020 Health Care Providers &amp; Services  
 9 220244 QANTAS AIRWAYS LTD     2024  203020 Passenger Airlines (New name)     
10 017525 ORIGIN ENERGY LTD      2024  551010 Electric Utilities                
# ℹ 190 more rows</code></pre>
</div>
</div>
<p>Surprisingly straight forward, right? As the above output shows, <code>left_join()</code> has used <code>gics_industry</code> to add a new variable, <code>industry</code>, to the right-hand end of <code>firms</code>. No other columns have been added, and all existing columns are as they were before the join. Furthermore, we have the same number of rows in our firms name data frame post-join as we had pre-join.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Defaults in `left_join()`">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Defaults in <code>left_join()</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>left_join(x, y)</code> does several things by default:</p>
<ol type="1">
<li>It uses all variables that appear in <strong>both</strong> data frames as the join key.
<ul>
<li>You can override this by explicitly specifying the variable(s) to use as the join key.</li>
</ul></li>
<li>It adds all columns from data frame <code>y</code> that do not already appear in data frame <code>x</code>.
<ul>
<li>You can override this by specifying exactly which columns from <code>y</code> should be joined to <code>x</code>.<br>
</li>
</ul></li>
</ol>
</div>
</div>
<p>Let’s try something more ambitious: using a join to add our price data to our financial statements data for the 200-largest ASX-listed firms in 2024. First, let’s again pull up and examine our financial statements data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>asx_200_2024 <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 30
   gvkey  curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt   dvp
   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 013312 USD   2024      6 6/30/20… 102362 9273       49120  2084  18634     NA
 2 210216 AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740     NA
 3 223003 USD   2024      6 6/30/20…  38022  849       19401   944  11239     NA
 4 212650 AUD   2024      6 6/30/20…  36694  104       11678  1590  18596     NA
 5 100894 AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411     NA
 6 212427 USD   2024      6 6/30/20…  30060 2834       19531   192   5208     NA
 7 101601 AUD   2024      6 6/30/20…  27309  923        8585  1165  10113     NA
 8 226744 AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.    NA
 9 220244 AUD   2024      6 6/30/20…  20564 2761         294   600   5991     NA
10 017525 AUD   2024      6 6/30/20…  20454  608        9489    68   3310     NA
# ℹ 19 more variables: ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;, sale &lt;dbl&gt;,
#   epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;, conml &lt;chr&gt;,
#   ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;, sector &lt;chr&gt;,
#   indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>As we discussed above, <code>gvkey</code> appears in <code>asx_200_2024</code>. Now, let’s pull up and examine our stock price data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   gvkey  conm                        fyear  price
   &lt;chr&gt;  &lt;chr&gt;                       &lt;chr&gt;  &lt;dbl&gt;
 1 005302 LABYRINTH RESOURCES LIMITED 2021   0.034
 2 005302 LABYRINTH RESOURCES LIMITED 2022   0.02 
 3 005302 LABYRINTH RESOURCES LIMITED 2023   0.006
 4 005302 LABYRINTH RESOURCES LIMITED 2024   0.017
 5 013312 BHP GROUP LTD               2021  37.6  
 6 013312 BHP GROUP LTD               2022  38.5  
 7 013312 BHP GROUP LTD               2023  44.2  
 8 013312 BHP GROUP LTD               2024  46.0  
 9 014242 ANSELL LTD                  2021  34.2  
10 014242 ANSELL LTD                  2022  25.2  </code></pre>
</div>
</div>
<p>We also see <code>gvkey</code> in our stock price data frame. So, why don’t we examine whether <code>gvkey</code> uniquely identifies the observations in <code>prices_tidy</code>, in which case we can use <code>gvkey</code> for our join.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many times each gvkey appears in prices_tidy</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for gvkeys that appear more than once (i.e., not unique)</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gvkey) <span class="sc">|&gt;</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,835 × 2
   gvkey      n
   &lt;chr&gt;  &lt;int&gt;
 1 005302     4
 2 010991     4
 3 013312     4
 4 014242     4
 5 014802     4
 6 015362     4
 7 015889     4
 8 016560     4
 9 016602     4
10 017525     4
# ℹ 1,825 more rows</code></pre>
</div>
</div>
<p>Lucky we checked because <code>gvkey</code> does not uniquely identify each observation in <code>prices_tidy</code>. Instead, we observe in many cases four instances of each gvkey value in our data frame. This occurs because while our financial statements data, <code>asx_200_2024</code>, covers a single firm-year (2024), our stock price data, <code>prices_tidy</code>, covers four firm-years (2021-2024). And so, we must use <code>gvkey</code> <em>and</em> <code>fyear</code> to join our data frames.</p>
<p>Before making this join, let’s confirm that for each data frame, this compound key (<code>gvkey</code> <em>and</em> <code>fyear</code>) uniquely identifies each observation (we refer to a primary key that uses a set of variables as a compound key):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many times each gvkey–fyear pair appears in asx_200_2024</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># If the compound key is unique, all counts should equal 1</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gvkey, fyear) <span class="sc">|&gt;</span> </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 3
   gvkey  fyear     n
   &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
 1 013312 2024      1
 2 014242 2024      1
 3 017525 2024      1
 4 100251 2024      1
 5 100442 2024      1
 6 100461 2024      1
 7 100894 2024      1
 8 101392 2024      1
 9 101513 2024      1
10 101568 2024      1
# ℹ 190 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count how many times each gvkey–fyear pair appears in prices_tidy</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># If the compound key is unique, all counts should equal 1</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(gvkey, fyear) <span class="sc">|&gt;</span> </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,340 × 3
   gvkey  fyear     n
   &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
 1 005302 2021      1
 2 005302 2022      1
 3 005302 2023      1
 4 005302 2024      1
 5 010991 2021      1
 6 010991 2022      1
 7 010991 2023      1
 8 010991 2024      1
 9 013312 2021      1
10 013312 2022      1
# ℹ 7,330 more rows</code></pre>
</div>
</div>
<p>Great. We can use the compound key <code>gvkey</code> <em>and</em> <code>fyear</code> to join our data frames.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the financial statements data (asx_200_2024) with stock prices (prices_tidy)</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use gvkey and fyear together as the compound key</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep all rows from asx_200_2024 and add matching price column from prices_tidy</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>financials_prices_lj <span class="ot">&lt;-</span> </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    prices_tidy <span class="sc">|&gt;</span> <span class="fu">select</span>(gvkey, fyear, price),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder columns so price appears first, followed by the rest of the data</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>financials_prices_lj <span class="sc">|&gt;</span> </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(price, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 31
    price gvkey curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt
    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1  46.0  0133… USD   2024      6 6/30/20… 102362 9273       49120  2084  18634 
 2   3.88 2102… AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740 
 3 286.   2230… USD   2024      6 6/30/20…  38022  849       19401   944  11239 
 4  13.1  2126… AUD   2024      6 6/30/20…  36694  104       11678  1590  18596 
 5  33.3  1008… AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411 
 6  20.7  2124… USD   2024      6 6/30/20…  30060 2834       19531   192   5208 
 7  70.4  1016… AUD   2024      6 6/30/20…  27309  923        8585  1165  10113 
 8  41.6  2267… AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.
 9   7.42 2202… AUD   2024      6 6/30/20…  20564 2761         294   600   5991 
10  10.0  0175… AUD   2024      6 6/30/20…  20454  608        9489    68   3310 
# ℹ 190 more rows
# ℹ 20 more variables: dvp &lt;dbl&gt;, ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;,
#   sale &lt;dbl&gt;, epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;,
#   conml &lt;chr&gt;, ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;,
#   sector &lt;chr&gt;, indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Great. Now we have financial and stock price data, and so we can examine questions about the relationship between firms’ operating performance and capital market performance - e.g., do investors pay more for firms that generate higher earnings? We will leave questions like this one to this week’s tutorial exercises.</p>
<p>Before moving on, one thing you might have noticed, however, is that in combining our financial and stock price data frames <code>left_join()</code> keeps all the rows in the financial statements data frame and only those rows; that is, it does not combine stock price data for firms that appear in our stock price data frame but that do not appear in our financial statements data frame (if you look closely at the output above, you can see that while <code>asx_200_2024</code> contains 200 rows-one for each of the 200-largest ASX firms in 2024-<code>prices_tidy</code> contains 7,340 rows-one for each firm-year for all ASX listed firms for the period 2021-2024). While all other mutating joins employ the same interface as <code>left_join()</code>, they differ in terms of which rows they keep.</p>
<p>For example, we can run the code below to see which rows <code>right_join()</code>, another type of mutating join, keeps:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the financial statements data (asx_200_2024) with stock prices (prices_tidy)</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Use gvkey and fyear as the compound key</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep all rows from prices_tidy (the "right" table), adding financials where available</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>financials_prices_rj <span class="ot">&lt;-</span> </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>    prices_tidy <span class="sc">|&gt;</span> <span class="fu">select</span>(gvkey, fyear, price),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder columns so price appears first, followed by the rest of the data</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>financials_prices_rj <span class="sc">|&gt;</span> </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(price, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,340 × 31
    price gvkey curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt
    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1  46.0  0133… USD   2024      6 6/30/20… 102362 9273       49120  2084  18634 
 2   3.88 2102… AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740 
 3 286.   2230… USD   2024      6 6/30/20…  38022  849       19401   944  11239 
 4  13.1  2126… AUD   2024      6 6/30/20…  36694  104       11678  1590  18596 
 5  33.3  1008… AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411 
 6  20.7  2124… USD   2024      6 6/30/20…  30060 2834       19531   192   5208 
 7  70.4  1016… AUD   2024      6 6/30/20…  27309  923        8585  1165  10113 
 8  41.6  2267… AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.
 9   7.42 2202… AUD   2024      6 6/30/20…  20564 2761         294   600   5991 
10  10.0  0175… AUD   2024      6 6/30/20…  20454  608        9489    68   3310 
# ℹ 7,330 more rows
# ℹ 20 more variables: dvp &lt;dbl&gt;, ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;,
#   sale &lt;dbl&gt;, epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;,
#   conml &lt;chr&gt;, ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;,
#   sector &lt;chr&gt;, indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>So, on face value the output looks much like that which we got from <code>left_join()</code>, but on closer inspection we now have 7,340 rows-the same as we have in <code>prices_tidy</code>.</p>
<p>We can see that <code>right_join(x, y)</code> keeps all rows in the <code>y</code> data frame. As such, our output from <code>right_join()</code> has many, many rows where we have missing values for the columns from <code>asx_200_2024</code> and only values for the price column (i.e., firms for which we have stock price data but not financial statements data).</p>
<p>We can observe this by counting the number of missing values in <code>financials_prices_rj</code> for any of columns from <code>asx_200_2024</code>. For example, we expect (and do find) that we have many missing values for <code>ebit</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(financials_prices_rj<span class="sc">$</span>ebit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7145</code></pre>
</div>
</div>
<div class="exercise">
<div class="exercise-time">
<p>10 min</p>
</div>
<p>As the name suggests, <code>full_join()</code> keeps all rows in either <code>x</code> or <code>y</code>. That is, the output contains all observations from <code>x</code> (even if no match in <code>y</code>) and all observations from <code>y</code> (even if no match in <code>x</code>).</p>
<p>Using <code>gvkey</code> <em>and</em> <code>fyear</code> as a compound key, join financial statements data (<code>asx_200_2024</code>) with stock prices (<code>prices_tidy</code>), then reorder columns so <code>price</code> appears first.</p>
<p>Finally, report the number of rows produced and explain why it can exceed the row count from <code>right_join()</code>.</p>
</div>
<div class="solution-header">
<p>Solution</p>
</div>
<div class="solution-content">
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full join on compound key (gvkey, fyear)</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>financials_prices_fj <span class="ot">&lt;-</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    prices_tidy <span class="sc">|&gt;</span> <span class="fu">select</span>(gvkey, fyear, price),</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reorder columns so price is first</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>financials_prices_fj <span class="sc">|&gt;</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(price, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,343 × 31
    price gvkey curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt
    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1  46.0  0133… USD   2024      6 6/30/20… 102362 9273       49120  2084  18634 
 2   3.88 2102… AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740 
 3 286.   2230… USD   2024      6 6/30/20…  38022  849       19401   944  11239 
 4  13.1  2126… AUD   2024      6 6/30/20…  36694  104       11678  1590  18596 
 5  33.3  1008… AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411 
 6  20.7  2124… USD   2024      6 6/30/20…  30060 2834       19531   192   5208 
 7  70.4  1016… AUD   2024      6 6/30/20…  27309  923        8585  1165  10113 
 8  41.6  2267… AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.
 9   7.42 2202… AUD   2024      6 6/30/20…  20564 2761         294   600   5991 
10  10.0  0175… AUD   2024      6 6/30/20…  20454  608        9489    68   3310 
# ℹ 7,333 more rows
# ℹ 20 more variables: dvp &lt;dbl&gt;, ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;,
#   sale &lt;dbl&gt;, epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;,
#   conml &lt;chr&gt;, ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;,
#   sector &lt;chr&gt;, indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Using <code>full_join()</code>, our output contains 7,343 rows - three more than in <code>financials_prices_fj</code>, the output that <code>right_join()</code> created.</p>
<p><code>full_join()</code> returns every key that appears in either table. That means it keeps:</p>
<ul>
<li><p>all matched firm–years (where both financials and prices exist),</p></li>
<li><p>plus firm–years that appear only in prices,</p></li>
<li><p>plus firm–years that appear only in financials.</p></li>
</ul>
<p>Because it retains both sets of unmatched keys, the row count can be larger than what you get from <code>right_join()</code> (which only guarantees all rows from the right-hand table).</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Identifying Non-Matching Observations">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Identifying Non-Matching Observations
</div>
</div>
<div class="callout-body-container callout-body">
<p>These three additional rows are observations from <code>asx_200_2024</code>, our financial statements data frame, that do not have a match in <code>prices_tidy</code>, the stock price data frame. In other words, they are <code>gvkey</code>–year combinations that appear in the financial statements but not in the stock price data.</p>
<p>To identify these cases, we use a specific type of join: <code>anti_join()</code>. Unlike the mutating joins we have used so far, <code>anti_join()</code> is a filtering join. It removes matching rows and keeps only the non-matching ones — more on this distinction later.</p>
</div>
</div>
<p>We can use <code>anti_join(x, y)</code> to identify and keep only those observations that appear in <code>asx_200_2024</code> (i.e., <code>x</code>) but that do not appear in <code>prices_tidy</code> (i.e., <code>y</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use anti_join() to keep only rows from asx_200_2024 </span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># that do NOT have a matching gvkey–fyear in prices_tidy</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This helps identify implicit missing values (observations present in x but absent in y)</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>financials_prices_aj <span class="ot">&lt;-</span> </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>    prices_tidy,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the unmatched observations</span></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>financials_prices_aj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 30
  gvkey  curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt   dvp
  &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 267188 AUD   2024      6 6/30/2024 3477.  7.3        324.  340.     1.3    NA
2 270244 AUD   2024      7 7/31/2024 2376. 52          255   162.  1467.     NA
3 364417 AUD   2024      6 6/30/2024  362.  3.92        82.9  37.3   69.1    NA
# ℹ 19 more variables: ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;, sale &lt;dbl&gt;,
#   epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;, conml &lt;chr&gt;,
#   ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;, sector &lt;chr&gt;,
#   indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We see that our output from using <code>anti_join()</code> contains three rows, exactly the number we expected given the difference in the number of rows found in the output from when we used <code>right_join()</code> and when we used <code>full_join()</code>.</p>
<p>To confirm that these observations are in fact those from <code>x</code> that have no match in <code>y</code>, we can examine whether these gvkey-year combinations from our financial statements data frame appear in our stock price data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether gvkey 267188 in year 2024 appears in prices_tidy</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gvkey <span class="sc">==</span> <span class="st">"267188"</span>, fyear <span class="sc">==</span> <span class="st">"2024"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: gvkey &lt;chr&gt;, conm &lt;chr&gt;, fyear &lt;chr&gt;, price &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether gvkey 270244 in year 2024 appears in prices_tidy</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gvkey <span class="sc">==</span> <span class="st">"270244"</span>, fyear <span class="sc">==</span> <span class="st">"2024"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: gvkey &lt;chr&gt;, conm &lt;chr&gt;, fyear &lt;chr&gt;, price &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check whether gvkey 364417 in year 2024 appears in prices_tidy</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gvkey <span class="sc">==</span> <span class="st">"364417"</span>, fyear <span class="sc">==</span> <span class="st">"2024"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 4
# ℹ 4 variables: gvkey &lt;chr&gt;, conm &lt;chr&gt;, fyear &lt;chr&gt;, price &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Great. Those observations from <code>asx_200_2024</code> that <code>anti_join()</code> showed us to be missing from <code>prices_tidy</code> are in fact missing when we manually search for these observations using their unique gvkey-year combination.</p>
<p>The final mutating join that we consider is the <code>inner_join()</code>, which is effectively the inverse of <code>anti_join()</code>-that is, <code>inner_join(x, y)</code> only keeps rows that appear in both <code>x</code> and <code>y</code> and then adds columns from <code>y</code> to <code>x</code>. Let’s examine our output when we use <code>inner_join()</code> to combine our financial statements data and our stock price data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use inner_join() to keep only rows where gvkey–fyear combinations </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># appear in BOTH asx_200_2024 (financials) and prices_tidy (stock prices).</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This is effectively the inverse of anti_join().</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>financials_prices_ij <span class="ot">&lt;-</span> </span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Join with prices_tidy to add the stock price column</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select only the join keys and the price variable</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>    prices_tidy <span class="sc">|&gt;</span> </span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(gvkey, fyear, price),</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Match on the compound key (gvkey + fyear)</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the resulting joined data</span></span>
<span id="cb63-16"><a href="#cb63-16" aria-hidden="true" tabindex="-1"></a>financials_prices_ij</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 197 × 31
   gvkey  curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt   dvp
   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 013312 USD   2024      6 6/30/20… 102362 9273       49120  2084  18634     NA
 2 210216 AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740     NA
 3 223003 USD   2024      6 6/30/20…  38022  849       19401   944  11239     NA
 4 212650 AUD   2024      6 6/30/20…  36694  104       11678  1590  18596     NA
 5 100894 AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411     NA
 6 212427 USD   2024      6 6/30/20…  30060 2834       19531   192   5208     NA
 7 101601 AUD   2024      6 6/30/20…  27309  923        8585  1165  10113     NA
 8 226744 AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.    NA
 9 220244 AUD   2024      6 6/30/20…  20564 2761         294   600   5991     NA
10 017525 AUD   2024      6 6/30/20…  20454  608        9489    68   3310     NA
# ℹ 187 more rows
# ℹ 20 more variables: ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;, sale &lt;dbl&gt;,
#   epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;, conml &lt;chr&gt;,
#   ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;, sector &lt;chr&gt;,
#   indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;, price &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Interesting! The output from the inner join contains 197 observations, three fewer than we find in <code>asx_200_2024</code>, our financial statements data frame. You guessed it: these ‘missing’ observations from our financial statements data frame are those and only those that appear in our output when we use <code>anti_join()</code>. Neat, now we have shown how the different mutating joins work to combine data from a pair of data frames into a single data frame.</p>
</section>
<section id="selecting-rows-from-a-data-frame-with-filtering-joins" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="selecting-rows-from-a-data-frame-with-filtering-joins"><span class="header-section-number">6.5.3</span> Selecting rows from a data frame with filtering joins</h3>
<div class="callout callout-style-default callout-important callout-titled" title="What are Filtering Joins?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What are Filtering Joins?
</div>
</div>
<div class="callout-body-container callout-body">
<p>As the name suggests, filtering joins work by filtering rows, and unlike mutating joins they do not add columns to a data frame. Instead, they determine which observations to keep or drop based on whether matches exist between two data frames.</p>
<p>The function <code>anti_join(x, y)</code> is a type of filtering join. It returns all rows in <code>x</code> that do not have a match in <code>y</code>. Filtering joins also include <code>semi_join(x, y)</code>, which works in the opposite way: it keeps rows in <code>x</code> only if they have a match in <code>y</code>. Together, <code>semi_join()</code> and <code>anti_join()</code> provide powerful tools for examining overlap between data sets and identifying gaps in coverage.</p>
</div>
</div>
<div class="exercise">
<div class="exercise-time">
<p>3 min</p>
</div>
<p>Use <code>colnames()</code> to compare the variables in the data frame created with <code>anti_join()</code> (<code>financials_prices_aj</code>) to those in the original <code>asx_200_2024</code> data frame.</p>
<ul>
<li>What do you observe about the column sets?<br>
</li>
<li>What does this imply about how filtering joins like <code>anti_join()</code> work compared to mutating joins such as <code>inner_join()</code> or <code>full_join()</code>?</li>
</ul>
</div>
<div class="solution-header">
<p>Solution</p>
</div>
<div class="solution-content">
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Column names in the anti_join result</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>financials_prices_aj <span class="sc">|&gt;</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gvkey"            "curcd"            "fyear"            "fyr"             
 [5] "datadate"         "at"               "capx"             "shareequity"     
 [9] "dlc"              "dltt"             "dvp"              "ebit"            
[13] "netprofit"        "pstk"             "sale"             "epsexcon"        
[17] "nicon"            "conm"             "fic"              "conml"           
[21] "ggroup"           "gind"             "gsector"          "gsubind"         
[25] "sector"           "indgroup"         "industry"         "subind"          
[29] "debt"             "invested_capital"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Column names in the original financial statements data</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>asx_200_2024 <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "gvkey"            "curcd"            "fyear"            "fyr"             
 [5] "datadate"         "at"               "capx"             "shareequity"     
 [9] "dlc"              "dltt"             "dvp"              "ebit"            
[13] "netprofit"        "pstk"             "sale"             "epsexcon"        
[17] "nicon"            "conm"             "fic"              "conml"           
[21] "ggroup"           "gind"             "gsector"          "gsubind"         
[25] "sector"           "indgroup"         "industry"         "subind"          
[29] "debt"             "invested_capital"</code></pre>
</div>
</div>
<p>The two sets of column names are identical. This occurs because filtering joins (<code>anti_join()</code>, <code>semi_join()</code>) only filter rows of the <code>x</code> data frame using <code>y</code>; they do not add variables from <code>y</code>.</p>
<p>By contrast, mutating joins (<code>inner_join()</code>, <code>left_join()</code>, <code>right_join()</code>, <code>full_join()</code>) combine columns from both data frames when keys match.</p>
<p>This comparison makes clear that filtering joins are useful when the goal is to select or exclude observations, while mutating joins are used to add new information from another data frame.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Missing values and `anti_join()`?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Missing values and <code>anti_join()</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>At first glance, <code>anti_join()</code> may not seem especially useful. However, it is a powerful tool for solving a common problem when working with real data: identifying implicit missing values.</p>
<p>Most of the time, missing values show up explicitly as <code>NA</code> in a data frame. But sometimes the issue is more subtle: an observation is missing entirely and therefore leaves no trace in the data. These gaps are often just as important as the data that is present.</p>
<p>By comparing two related data frames, <code>anti_join()</code> lets us find these implicit missing values. This makes <code>anti_join()</code> particularly valuable for:</p>
<ul>
<li>Diagnosing incomplete data coverage<br>
</li>
<li>Checking for firms, years, or categories that should appear but don’t<br>
</li>
<li>Ensuring consistency when merging multiple sources of information</li>
</ul>
<p>In practice, <code>anti_join(x, y)</code> returns rows in <code>x</code> that have no match in <code>y</code>—exactly the kind of check you need when searching for hidden gaps.</p>
</div>
</div>
<p>Let’s look at an example of implicit missing values in <code>asx_200_2024</code>, our stock price data frame. We identified these when we used anti_join() earlier to create the following data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>financials_prices_aj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 30
  gvkey  curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt   dvp
  &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
1 267188 AUD   2024      6 6/30/2024 3477.  7.3        324.  340.     1.3    NA
2 270244 AUD   2024      7 7/31/2024 2376. 52          255   162.  1467.     NA
3 364417 AUD   2024      6 6/30/2024  362.  3.92        82.9  37.3   69.1    NA
# ℹ 19 more variables: ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;, sale &lt;dbl&gt;,
#   epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;, conml &lt;chr&gt;,
#   ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;, sector &lt;chr&gt;,
#   indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Now, if we look at our stock price data frame, we have many rows that contain missing values, but these observations do not include those that we identified by using <code>anti_join()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>prices_tidy <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,133 × 4
   gvkey  conm                    fyear price
   &lt;chr&gt;  &lt;chr&gt;                   &lt;chr&gt; &lt;dbl&gt;
 1 016602 THE IQ GROUP GLOBAL LTD 2022     NA
 2 016602 THE IQ GROUP GLOBAL LTD 2023     NA
 3 016602 THE IQ GROUP GLOBAL LTD 2024     NA
 4 023681 SENEX ENERGY LTD        2022     NA
 5 023681 SENEX ENERGY LTD        2023     NA
 6 023681 SENEX ENERGY LTD        2024     NA
 7 037798 TRITIUM DCFC LTD        2024     NA
 8 039960 IRIS ENERGY LIMITED     2021     NA
 9 040702 LOCAFY LTD              2021     NA
10 040702 LOCAFY LTD              2024     NA
# ℹ 1,123 more rows</code></pre>
</div>
</div>
<p>The gvkeys in <code>financials_prices_aj</code> do not appear in the above, not even as <code>NA</code> (check for using <code>filter()</code>).</p>
<p>Comparing these two data frames should make clear that we have two types of missing data: missing values that are explicitly recorded as such in a data frame, and so are directly observable-i.e., those above; and implicit missing values that we identify by their absence-i.e., those that we identify above using <code>anti_join()</code>.</p>
<p>We now consider our final join for this week’s topic, <code>semi_join()</code>, which is a filtering join that keeps all rows in <code>x</code> that have a match in <code>y</code>. Let’s see it in action:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use semi_join() to keep only those rows in asx_200_2024 (x)</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="co"># that also have a matching gvkey–fyear combination in prices_tidy (y)</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>financials_prices_sj <span class="ot">&lt;-</span> </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  asx_200_2024 <span class="sc">|&gt;</span> </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>    prices_tidy,</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">join_by</span>(gvkey, fyear)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the resulting data frame</span></span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a><span class="co"># This shows the subset of financial statements that also have matching stock price data</span></span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>financials_prices_sj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 197 × 30
   gvkey  curcd fyear   fyr datadate     at  capx shareequity   dlc   dltt   dvp
   &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1 013312 USD   2024      6 6/30/20… 102362 9273       49120  2084  18634     NA
 2 210216 AUD   2024      6 6/30/20…  45550 2288       17352  4228  12740     NA
 3 223003 USD   2024      6 6/30/20…  38022  849       19401   944  11239     NA
 4 212650 AUD   2024      6 6/30/20…  36694  104       11678  1590  18596     NA
 5 100894 AUD   2024      6 6/30/20…  33936 2548        5570  2311  14411     NA
 6 212427 USD   2024      6 6/30/20…  30060 2834       19531   192   5208     NA
 7 101601 AUD   2024      6 6/30/20…  27309  923        8585  1165  10113     NA
 8 226744 AUD   2024      6 6/30/20…  20894  754.       5275.  606. 10332.    NA
 9 220244 AUD   2024      6 6/30/20…  20564 2761         294   600   5991     NA
10 017525 AUD   2024      6 6/30/20…  20454  608        9489    68   3310     NA
# ℹ 187 more rows
# ℹ 19 more variables: ebit &lt;dbl&gt;, netprofit &lt;dbl&gt;, pstk &lt;dbl&gt;, sale &lt;dbl&gt;,
#   epsexcon &lt;dbl&gt;, nicon &lt;dbl&gt;, conm &lt;chr&gt;, fic &lt;chr&gt;, conml &lt;chr&gt;,
#   ggroup &lt;dbl&gt;, gind &lt;dbl&gt;, gsector &lt;dbl&gt;, gsubind &lt;dbl&gt;, sector &lt;chr&gt;,
#   indgroup &lt;chr&gt;, industry &lt;chr&gt;, subind &lt;chr&gt;, debt &lt;dbl&gt;,
#   invested_capital &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This subset of observations from our financial statements data frame should look familiar because these 197 observations are the same that we outputted when we used inner_join<code>()</code>, except the difference here is that <code>semi_join()</code> does not add any columns to these observations (whereas when we used <code>inner_join()</code> we added the column <code>price</code> to <code>asx_200_2024</code> for these observations).</p>
</section>
</section>
<section id="bringing-it-all-together-reshaping-and-combining-data" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="bringing-it-all-together-reshaping-and-combining-data"><span class="header-section-number">6.6</span> Bringing it all together: Reshaping and Combining Data</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Why reshaping and joining matter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why reshaping and joining matter
</div>
</div>
<div class="callout-body-container callout-body">
<p>In practice, no single dataset ever contains all the information needed to answer a business question. Some data arrives in messy, inconvenient formats that must be reshaped before analysis, while other data needs to be linked across multiple sources. Mastering pivots and joins ensures that analysts can prepare clean, consistent data sets ready for deeper analysis and visualization.</p>
</div>
</div>
<p>In this module, we have introduced two essential families of tools for working with business data: pivots for reshaping messy data into tidy form, and joins for combining multiple data frames into one.</p>
<p>First, we showed how <code>pivot_longer()</code> can be used to tidy “short and wide” stock price data by stacking year columns into a single year variable, with prices stored in one column. We also extended this to more complex messy data where column names contained both variable names and values (e.g., <code>price_2023</code>, <code>eps_2023</code>), demonstrating how the <code>.value</code> argument helps split these into tidy variables.</p>
<p>Second, we showed how <code>pivot_wider()</code> can tidy “long and narrow” financials data by collapsing repeated firm-year rows into a single row with columns for each financial measure. This ensured that each observation (a firm-year) was represented once, with measures like assets, sales, and EBIT stored as variables in their own columns.</p>
<p>Third, we turned to joins. We used <code>left_join()</code> to enrich a data frame of firms with information from a lookup table of industries, illustrating how primary keys and foreign keys connect observations across data frames. We then joined financial statement data with stock price data, showing how compound keys (<code>gvkey</code> and <code>fyear</code>) are often necessary when a single variable does not uniquely identify observations.</p>
<p>Fourth, we explored how different joins handle matching and non-matching observations. <code>left_join()</code> kept all rows from the financial statements; <code>right_join()</code> kept all rows from the stock prices; and <code>full_join()</code> kept rows from both. To dig deeper into non-matching cases, we used <code>anti_join()</code> to identify gvkey–year combinations present in one data frame but absent in another, demonstrating how anti-joins help reveal implicit missing values. Conversely, <code>inner_join()</code> and <code>semi_join()</code> kept only matching rows, letting us focus on overlap between datasets.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Key Takeaway">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Takeaway
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pivots allow us to reshape messy data into a tidy, consistent structure that the tidyverse is built to handle, while joins allow us to combine information from multiple sources into a single analytic data set. These two skills — tidying with pivots and joining with keys — form the foundation for reliable, transparent, and efficient business analytics.</p>
</div>
</div>
</section>
<section id="conclusion" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">6.7</span> Conclusion</h2>
<p>In this chapter, we have explored how to use the <code>tidyr</code> and <code>dplyr</code> packages to reshape and combine financial data in R. We learned how to tidy messy datasets using <code>pivot_longer()</code> and <code>pivot_wider()</code>, ensuring that variables are stored in columns and observations in rows. We then turned to joins, using keys to link together information from multiple sources. Through <code>left_join()</code>, <code>right_join()</code>, <code>full_join()</code>, and <code>inner_join()</code>, as well as filtering joins like <code>semi_join()</code> and <code>anti_join()</code>, we saw how different types of joins either add variables or filter rows, depending on the analytical task. By applying these techniques to data on the 200 largest Australian public companies in 2024, we created richer datasets that combined firm financials, industry classifications, and stock market performance.</p>
<p>In the next chapter, we will shift our focus to the formats in which data is stored and exchanged. We will identify common formats such as CSV, JSON, SQL, and Parquet, and consider when each is most appropriate for business use. We will practice loading, exploring, and manipulating data from flat files and nested JSON, and use tools like <code>dbplyr</code> and <code>arrow</code> to query data in DuckDB and Parquet.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../insights/data_manipulation.html" class="pagination-link" aria-label="Data Wrangling for Business Analytics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Wrangling for Business Analytics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../data_management/data_storage.html" class="pagination-link" aria-label="Storing and Using Existing Data">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Storing and Using Existing Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>