<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Forming and Evaluating Data-Driven Predictions – Foundations of Business Analytics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../data_management/data_storage.html" rel="next">
<link href="../advanced_analytics/causal_analytics.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e793f7ea19fa229457e8560bce3db5d7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../solution.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../advanced_analytics/data_variation.html">Extracting Deeper Insights from Data</a></li><li class="breadcrumb-item"><a href="../advanced_analytics/predictive_analytics.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Forming and Evaluating Data-Driven Predictions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Foundations of Business Analytics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/what_is_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What is Business Analytics?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/how_to_do_business_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Core Skills of a “Business Scientist”</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../foundations/reproducible.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Workflows with R &amp; Posit Cloud</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Our First Insights from Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualisation for Business Intelligence</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_manipulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Wrangling for Business Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../insights/data_tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shaping and Combining Data for Business Analytics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Extracting Deeper Insights from Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced_analytics/data_variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Variation in Cross-Sectional, Times-Series, and Panel Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced_analytics/descriptive_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Descriptive Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced_analytics/causal_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causal Analytics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../advanced_analytics/predictive_analytics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Forming and Evaluating Data-Driven Predictions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Finding and Storing Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_management/data_storage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Storing and Using Existing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_management/data_collection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Collecting Structured and Unstructured Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Ethics in Analytics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../ethics_privacy/ethics_privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Ethics in Business Analytics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Tutorials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/core_skills_genai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 1: Core Skills of a Business Scientist in the GenAI Era</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/intro_r_quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 2: From Data to a Managerial Briefing with R and Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 3: Data Visualization for Business Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 4: Data Wrangling for Business Analytics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 5: Shaping and Joining Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/data_variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 6: Using Variation in Data to Tell a Story</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/descriptive_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 7: Descriptive Analytics in HRM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tutorials/causal_analytics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tutorial 8: Causal Analytics &amp; Improving User Sign Up Experiences</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-business-challenge" id="toc-the-business-challenge" class="nav-link active" data-scroll-target="#the-business-challenge"><span class="header-section-number">10.1</span> The Business Challenge</a>
  <ul class="collapse">
  <li><a href="#the-topic-demand-forecasting-for-workforce-planning" id="toc-the-topic-demand-forecasting-for-workforce-planning" class="nav-link" data-scroll-target="#the-topic-demand-forecasting-for-workforce-planning">The Topic: Demand Forecasting for Workforce Planning</a></li>
  <li><a href="#the-setting-attendance-at-major-league-baseball-games" id="toc-the-setting-attendance-at-major-league-baseball-games" class="nav-link" data-scroll-target="#the-setting-attendance-at-major-league-baseball-games">The Setting: Attendance at Major League Baseball Games</a></li>
  <li><a href="#what-makes-this-a-prediction-problem" id="toc-what-makes-this-a-prediction-problem" class="nav-link" data-scroll-target="#what-makes-this-a-prediction-problem">What Makes This a Prediction Problem?</a></li>
  </ul></li>
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data"><span class="header-section-number">10.2</span> Loading the Data</a>
  <ul class="collapse">
  <li><a href="#r-packages-for-today" id="toc-r-packages-for-today" class="nav-link" data-scroll-target="#r-packages-for-today">R Packages for Today</a></li>
  <li><a href="#loading-the-cubs-attendance-data" id="toc-loading-the-cubs-attendance-data" class="nav-link" data-scroll-target="#loading-the-cubs-attendance-data">Loading the Cubs Attendance Data</a></li>
  </ul></li>
  <li><a href="#understanding-the-outcome-we-want-to-predict" id="toc-understanding-the-outcome-we-want-to-predict" class="nav-link" data-scroll-target="#understanding-the-outcome-we-want-to-predict"><span class="header-section-number">10.3</span> Understanding the Outcome We Want to Predict</a>
  <ul class="collapse">
  <li><a href="#how-is-home-game-attendance-distributed" id="toc-how-is-home-game-attendance-distributed" class="nav-link" data-scroll-target="#how-is-home-game-attendance-distributed">How Is Home-Game Attendance Distributed?</a></li>
  </ul></li>
  <li><a href="#training-data-and-test-data" id="toc-training-data-and-test-data" class="nav-link" data-scroll-target="#training-data-and-test-data"><span class="header-section-number">10.4</span> Training Data and Test Data</a>
  <ul class="collapse">
  <li><a href="#why-do-we-need-separate-training-and-test-data" id="toc-why-do-we-need-separate-training-and-test-data" class="nav-link" data-scroll-target="#why-do-we-need-separate-training-and-test-data">Why Do We Need Separate Training and Test Data?</a></li>
  </ul></li>
  <li><a href="#forming-simple-predictions" id="toc-forming-simple-predictions" class="nav-link" data-scroll-target="#forming-simple-predictions"><span class="header-section-number">10.5</span> Forming Simple Predictions</a>
  <ul class="collapse">
  <li><a href="#starting-simple-use-the-previous-home-game" id="toc-starting-simple-use-the-previous-home-game" class="nav-link" data-scroll-target="#starting-simple-use-the-previous-home-game">Starting Simple: Use the Previous Home Game</a></li>
  <li><a href="#what-about-two-games-ago" id="toc-what-about-two-games-ago" class="nav-link" data-scroll-target="#what-about-two-games-ago">What About Two Games Ago?</a></li>
  </ul></li>
  <li><a href="#evaluating-predictions-during-model-development" id="toc-evaluating-predictions-during-model-development" class="nav-link" data-scroll-target="#evaluating-predictions-during-model-development"><span class="header-section-number">10.6</span> Evaluating Predictions During Model Development</a>
  <ul class="collapse">
  <li><a href="#predictions-are-not-enough" id="toc-predictions-are-not-enough" class="nav-link" data-scroll-target="#predictions-are-not-enough">Predictions Are Not Enough</a></li>
  <li><a href="#comparing-lag-1-and-lag-2" id="toc-comparing-lag-1-and-lag-2" class="nav-link" data-scroll-target="#comparing-lag-1-and-lag-2">Comparing Lag 1 and Lag 2</a></li>
  </ul></li>
  <li><a href="#combining-recent-information" id="toc-combining-recent-information" class="nav-link" data-scroll-target="#combining-recent-information"><span class="header-section-number">10.7</span> Combining Recent Information</a>
  <ul class="collapse">
  <li><a href="#a-two-game-trailing-mean" id="toc-a-two-game-trailing-mean" class="nav-link" data-scroll-target="#a-two-game-trailing-mean">A Two-Game Trailing Mean</a></li>
  <li><a href="#comparing-recent-history-prediction-rules" id="toc-comparing-recent-history-prediction-rules" class="nav-link" data-scroll-target="#comparing-recent-history-prediction-rules">Comparing Recent-History Prediction Rules</a></li>
  </ul></li>
  <li><a href="#using-more-relevant-historical-games" id="toc-using-more-relevant-historical-games" class="nav-link" data-scroll-target="#using-more-relevant-historical-games"><span class="header-section-number">10.8</span> Using More Relevant Historical Games</a>
  <ul class="collapse">
  <li><a href="#predicting-attendance-by-opponent" id="toc-predicting-attendance-by-opponent" class="nav-link" data-scroll-target="#predicting-attendance-by-opponent">Predicting Attendance by Opponent</a></li>
  <li><a href="#reusing-the-same-prediction-logic" id="toc-reusing-the-same-prediction-logic" class="nav-link" data-scroll-target="#reusing-the-same-prediction-logic">Reusing the Same Prediction Logic</a></li>
  </ul></li>
  <li><a href="#comparing-candidate-prediction-rules" id="toc-comparing-candidate-prediction-rules" class="nav-link" data-scroll-target="#comparing-candidate-prediction-rules"><span class="header-section-number">10.9</span> Comparing Candidate Prediction Rules</a>
  <ul class="collapse">
  <li><a href="#evaluating-the-rules-on-the-training-data" id="toc-evaluating-the-rules-on-the-training-data" class="nav-link" data-scroll-target="#evaluating-the-rules-on-the-training-data">Evaluating the Rules on the Training Data</a></li>
  </ul></li>
  <li><a href="#evaluating-predictions-on-unseen-data" id="toc-evaluating-predictions-on-unseen-data" class="nav-link" data-scroll-target="#evaluating-predictions-on-unseen-data"><span class="header-section-number">10.10</span> Evaluating Predictions on Unseen Data</a>
  <ul class="collapse">
  <li><a href="#moving-from-training-to-test-data" id="toc-moving-from-training-to-test-data" class="nav-link" data-scroll-target="#moving-from-training-to-test-data">Moving from Training to Test Data</a></li>
  <li><a href="#applying-the-recent-history-rules-to-2025" id="toc-applying-the-recent-history-rules-to-2025" class="nav-link" data-scroll-target="#applying-the-recent-history-rules-to-2025">Applying the Recent-History Rules to 2025</a></li>
  <li><a href="#applying-the-opponent-rules-to-2025" id="toc-applying-the-opponent-rules-to-2025" class="nav-link" data-scroll-target="#applying-the-opponent-rules-to-2025">Applying the Opponent Rules to 2025</a></li>
  <li><a href="#comparing-test-set-performance" id="toc-comparing-test-set-performance" class="nav-link" data-scroll-target="#comparing-test-set-performance">Comparing Test-Set Performance</a></li>
  <li><a href="#which-prediction-rule-is-best" id="toc-which-prediction-rule-is-best" class="nav-link" data-scroll-target="#which-prediction-rule-is-best">Which Prediction Rule Is Best?</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">10.11</span> Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../advanced_analytics/data_variation.html">Extracting Deeper Insights from Data</a></li><li class="breadcrumb-item"><a href="../advanced_analytics/predictive_analytics.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Forming and Evaluating Data-Driven Predictions</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Forming and Evaluating Data-Driven Predictions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Learning Goals
</div>
</div>
<div class="callout-body-container callout-body">
<p>By the end of this chapter, you should be able to:</p>
<ul>
<li>Explain what makes a business problem a prediction problem and identify what information is available when a prediction is made.</li>
<li>Construct simple prediction rules using recent historical outcomes and groups of similar observations.</li>
<li>Distinguish between training data and test data, and explain why both are needed.</li>
<li>Evaluate and compare prediction rules using MAE, RMSE, and MAPE, with attention to the business decision being supported.</li>
<li>Explain the general workflow of predictive analysis</li>
</ul>
</div>
</div>
<section id="the-business-challenge" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="the-business-challenge"><span class="header-section-number">10.1</span> The Business Challenge</h2>
<section id="the-topic-demand-forecasting-for-workforce-planning" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-topic-demand-forecasting-for-workforce-planning">The Topic: Demand Forecasting for Workforce Planning</h3>
<p>Many business decisions must be made before demand is known. Retailers decide how much stock to order, call centres decide how many staff to schedule, and restaurants decide how many employees to roster before customers arrive. Too many resources increase costs, while too few can lead to shortages, long queues, or poor service. Managers therefore need an estimate of future demand before making these decisions.</p>
<p>In this chapter, we focus on one part of this problem: <strong>using historical data to predict future demand</strong>.</p>
</section>
<section id="the-setting-attendance-at-major-league-baseball-games" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="the-setting-attendance-at-major-league-baseball-games">The Setting: Attendance at Major League Baseball Games</h3>
<p>Our setting is Major League Baseball (MLB), a professional baseball league in the United States and Canada. Each team plays some games in its own stadium. Before a home game, stadium managers need to decide how many staff to roster and how much food and drink to prepare. These decisions depend partly on how many people will attend.</p>
<p>Attendance is not known before the game takes place, but managers do have historical information. They know how many people attended previous home games, which opposing team will be visiting, and how attendance has varied across opponents.</p>
<p>Our task is:</p>
<blockquote class="blockquote">
<p><strong>How can we use historical attendance data to predict attendance at a future home game?</strong></p>
</blockquote>
<p>We will focus on forming and evaluating the attendance prediction. Turning that prediction into staffing and purchasing decisions is a separate problem.</p>
</section>
<section id="what-makes-this-a-prediction-problem" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="what-makes-this-a-prediction-problem">What Makes This a Prediction Problem?</h3>
<p>A prediction problem has two parts:</p>
<ol type="1">
<li>an outcome that we do not yet know; and</li>
<li>information that is available when we make the prediction.</li>
</ol>
<p>Here, the unknown outcome is attendance at a future home game, while historical attendance provides information that we can use to predict it. Timing matters: we can only use information that is known when the prediction is made. For example, we know which opponent will visit before the game takes place, but we do not know how many people will attend until the game occurs.</p>
<p>This gives us a rule that we will use throughout the chapter:</p>
<blockquote class="blockquote">
<p><strong>When predicting an outcome, we can use only information that was available before that outcome occurred.</strong></p>
</blockquote>
<p>When predicting attendance at an upcoming game, for example, we can use attendance from earlier games. We cannot use attendance from that game or from games that take place later. This rule will determine how we construct our prediction rules.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Prediction is not explanation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our goal in this chapter is to <strong>predict</strong> attendance, not to explain why attendance changes.</p>
<p>Suppose games against a particular opponent tend to have higher attendance. That pattern may help us predict attendance at a future game against the same opponent. It does not, by itself, show that playing that opponent causes attendance to increase.</p>
<p>For prediction, our question is narrower: <strong>does this information help us predict future attendance more accurately?</strong></p>
</div>
</div>
</section>
</section>
<section id="loading-the-data" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="loading-the-data"><span class="header-section-number">10.2</span> Loading the Data</h2>
<section id="r-packages-for-today" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="r-packages-for-today">R Packages for Today</h3>
<p>We begin by loading the R packages used in this chapter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(yardstick)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We have used the first three packages before. The <code>yardstick</code> package provides functions for evaluating predictions. We will use it later when we compare our prediction rules.</p>
</section>
<section id="loading-the-cubs-attendance-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="loading-the-cubs-attendance-data">Loading the Cubs Attendance Data</h3>
<p>Our data contain Chicago Cubs home games from 2022 to 2025. We load the data from <code>data/cubs_attendance.csv</code> and store them as <code>cubs_attendance</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 324 Columns: 22
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (11): tm, h_a, opp, result, record, gb, win, loss, save, d_n, orig_sche...
dbl   (9): gm, r, ra, inn, rank, attendance, c_li, streak, year
date  (1): date
time  (1): time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cubs_attendance <span class="ot">&lt;-</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read_csv</span>(<span class="st">"data/cubs_attendance.csv"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We inspect the data using <code>glimpse()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(cubs_attendance)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 324
Columns: 22
$ gm             &lt;dbl&gt; 1, 2, 3, 10, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27…
$ date           &lt;date&gt; 2022-04-07, 2022-04-09, 2022-04-10, 2022-04-18, 2022-0…
$ tm             &lt;chr&gt; "CHC", "CHC", "CHC", "CHC", "CHC", "CHC", "CHC", "CHC",…
$ h_a            &lt;chr&gt; "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", …
$ opp            &lt;chr&gt; "MIL", "MIL", "MIL", "TBR", "TBR", "TBR", "PIT", "PIT",…
$ result         &lt;chr&gt; "W", "W", "L", "W", "L", "L", "L", "L", "W", "L", "L", …
$ r              &lt;dbl&gt; 5, 9, 4, 4, 5, 2, 3, 2, 21, 3, 1, 3, 0, 2, 1, 9, 7, 2, …
$ ra             &lt;dbl&gt; 4, 0, 5, 2, 6, 8, 4, 4, 0, 4, 3, 4, 7, 6, 7, 0, 0, 3, 3…
$ inn            &lt;dbl&gt; NA, NA, NA, NA, NA, 6, NA, NA, NA, NA, NA, NA, NA, NA, …
$ record         &lt;chr&gt; "1-0", "2-0", "2-1", "6-4", "6-5", "6-6", "6-7", "6-8",…
$ rank           &lt;dbl&gt; 1, 1, 1, 1, 3, 3, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4…
$ gb             &lt;chr&gt; "Tied", "Tied", "Tied", "Tied", "1.0", "2.0", "2.0", "3…
$ win            &lt;chr&gt; "Givens", "Steele", "Cousins", "Thompson", "Fleming", "…
$ loss           &lt;chr&gt; "Ashby", "Woodruff", "Norris", "Adam", "Steele", "Strom…
$ save           &lt;chr&gt; "Robertson", NA, "Hader", "Robertson", "Kittredge", NA,…
$ time           &lt;time&gt; 03:18:00, 03:28:00, 03:03:00, 02:43:00, 03:09:00, 02:0…
$ d_n            &lt;chr&gt; "D", "D", "D", "N", "N", "N", "N", "N", "D", "D", "N", …
$ attendance     &lt;dbl&gt; 35112, 30369, 32858, 26615, 26568, 26167, 32341, 25005,…
$ c_li           &lt;dbl&gt; 1.00, 1.01, 1.07, 0.95, 0.97, 0.93, 0.97, 0.95, 0.88, 0…
$ streak         &lt;dbl&gt; 1, 2, -1, 2, -1, -2, -3, -4, 1, -1, -1, -2, -3, -4, -5,…
$ orig_scheduled &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "2022-0…
$ year           &lt;dbl&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2…</code></pre>
</div>
</div>
<p>Each row represents one Cubs home game. The data include the date, opposing team (<code>opp</code>), whether the game was played during the day or at night (<code>d_n</code>), attendance, and the season (<code>year</code>), along with other information about the game.</p>
<p>We also count how many home games appear in each season.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cubs_attendance <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(year, <span class="at">name =</span> <span class="st">"home_games"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
   year home_games
  &lt;dbl&gt;      &lt;int&gt;
1  2022         81
2  2023         81
3  2024         81
4  2025         81</code></pre>
</div>
</div>
</section>
</section>
<section id="understanding-the-outcome-we-want-to-predict" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="understanding-the-outcome-we-want-to-predict"><span class="header-section-number">10.3</span> Understanding the Outcome We Want to Predict</h2>
<section id="how-is-home-game-attendance-distributed" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="how-is-home-game-attendance-distributed">How Is Home-Game Attendance Distributed?</h3>
<p>Before constructing prediction rules, we first look at the outcome we want to predict: attendance at Chicago Cubs home games.</p>
<p>We start with the 2022 and 2023 seasons and compare their attendance distributions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cubs_attendance <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">2022</span>, <span class="dv">2023</span>)) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> attendance)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2500</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> year) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Chicago Cubs Home-Game Attendance"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Attendance"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of games"</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="predictive_analytics_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The two seasons cover a similar overall range, from roughly the mid-20,000s to around 40,000 attendees, but the distributions differ within that range. Attendance in 2022 is more concentrated around 30,000–35,000, while 2023 has more games spread across the upper part of the distribution.</p>
<p>Attendance also varies substantially from game to game within each season. This gives us something to predict. Rather than using the same attendance forecast for every game, we can ask whether information from previous games helps us anticipate which games will have higher or lower attendance.</p>
<p>The upper end of both distributions also stops at around the same level. This reflects a feature of the setting: stadium attendance cannot exceed the number of people the stadium can hold.</p>
<div class="exercise">
<div class="exercise-time">
<p>5 min</p>
</div>
<p>Using the two histograms:</p>
<ol type="1">
<li>What range of attendance is common across the two seasons?</li>
<li>How does the shape of the attendance distribution differ between 2022 and 2023?</li>
<li>What do you notice about the upper end of the distributions?</li>
<li>Why does the variation across games give us a reason to build prediction rules?</li>
</ol>
</div>
<p>Comparing the two histograms lets us see whether attendance falls within a similar range across seasons and whether the overall shape of the distribution changes much from one year to the next.</p>
<p>Attendance also varies from game to game within each season. If that variation can be predicted using information from earlier games or other game characteristics, then a single forecast for every game can be improved upon.</p>
<p>Attendance has a natural upper bound: a stadium can hold only a fixed number of people. We should therefore also look for signs that attendance becomes compressed near its upper end.</p>
</section>
</section>
<section id="training-data-and-test-data" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="training-data-and-test-data"><span class="header-section-number">10.4</span> Training Data and Test Data</h2>
<section id="why-do-we-need-separate-training-and-test-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="why-do-we-need-separate-training-and-test-data">Why Do We Need Separate Training and Test Data?</h3>
<p>Suppose we want to predict attendance at future Cubs games. We might try several prediction rules, compare how well they work on the historical games, and keep the rule that performs best. If we then use those same historical games to report how accurate our chosen rule is, we have a problem: the historical outcomes helped us decide which rule to keep. The selected rule may therefore look especially good on those particular games, even if it does not perform as well on new games.</p>
<p>What we really want to know is whether the rule can predict observations that played no role in choosing it. To answer that question, we divide the data into two parts. The <strong>training data</strong> are the observations we use to develop, compare, and choose prediction rules. The <strong>test data</strong> are observations kept separate during model development and used only at the end to evaluate how well the chosen rules perform on new data.</p>
<p>For this chapter, we use:</p>
<ul>
<li><strong>Training data:</strong> Cubs home games from 2022–2024</li>
<li><strong>Test data:</strong> Cubs home games from 2025</li>
</ul>
<p>The logic is simple: use the earlier seasons to develop the prediction rules, then evaluate those rules on a later season that played no role in choosing them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="ot">&lt;-</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  cubs_attendance <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&lt;=</span> <span class="dv">2024</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>cubs_test <span class="ot">&lt;-</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  cubs_attendance <span class="sc">|&gt;</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2025</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can check how many games are available in each dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(cubs_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 243</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(cubs_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81</code></pre>
</div>
</div>
<p>For now, we work only with <code>cubs_train</code>. We will use those games to build and compare several candidate prediction rules. We will return to <code>cubs_test</code> only after those rules have been developed, so the 2025 games can show how well the rules perform on data that played no role in selecting them.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>A Simplified Test-Set Design
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter, we keep the 2025 test data completely separate from the 2022–2024 training data.</p>
<p>A more realistic forecasting system might update predictions during 2025 as new game outcomes become available. For example, attendance at an early-season game could be used when predicting a later game.</p>
<p>We will not do that here. Keeping the training period fixed makes the training/test distinction easier to see and avoids complicating the code further.</p>
</div>
</div>
</section>
</section>
<section id="forming-simple-predictions" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="forming-simple-predictions"><span class="header-section-number">10.5</span> Forming Simple Predictions</h2>
<section id="starting-simple-use-the-previous-home-game" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="starting-simple-use-the-previous-home-game">Starting Simple: Use the Previous Home Game</h3>
<p>We begin with a simple prediction rule: predict attendance at the next Cubs home game using attendance at the previous home game in the same season. The idea is that recent attendance may contain useful information about near-term demand. If the previous home game drew 35,000 people, our prediction for the next home game is 35,000.</p>
<p>For game (t), this rule is:</p>
<p><span class="math display">\[
\widehat{A}_t = A_{t-1}
\]</span></p>
<p>where (A_t) is attendance at game (t) and (_t) is our prediction for that game.</p>
<p>We can construct this prediction with <code>lag()</code>. We first order games within each season, then create a new variable containing attendance at the previous home game.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="ot">&lt;-</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year, gm) <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_lag1 =</span> <span class="fu">lag</span>(attendance, <span class="dv">1</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Because we calculate the lag separately within each season, the first home game of each year has no previous home game to use. Its <code>pred_lag1</code> value is therefore <code>NA</code>. This is not an error: the information required by the prediction rule is not yet available.</p>
</section>
<section id="what-about-two-games-ago" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="what-about-two-games-ago">What About Two Games Ago?</h3>
<p>Recent information may be useful, but we do not yet know how quickly that information becomes less helpful. A second prediction rule uses attendance from two home games earlier:</p>
<p><span class="math display">\[
\widehat{A}_t = A_{t-2}
\]</span></p>
<p>We add this prediction using a two-game lag.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="ot">&lt;-</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year, gm) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_lag2 =</span> <span class="fu">lag</span>(attendance, <span class="dv">2</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now the first two home games of each season have no <code>pred_lag2</code> value. Again, this follows directly from the rule: before the third home game, there is no attendance observation from two home games earlier.</p>
<p>We can inspect the actual attendance and both predictions side by side.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, gm, date, attendance, pred_lag1, pred_lag2) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 6
    year    gm date       attendance pred_lag1 pred_lag2
   &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1  2022     1 2022-04-07      35112        NA        NA
 2  2022     2 2022-04-09      30369     35112        NA
 3  2022     3 2022-04-10      32858     30369     35112
 4  2022    10 2022-04-18      26615     32858     30369
 5  2022    11 2022-04-19      26568     26615     32858
 6  2022    12 2022-04-20      26167     26568     26615
 7  2022    13 2022-04-21      32341     26167     26568
 8  2022    14 2022-04-22      25005     32341     26167
 9  2022    15 2022-04-23      39917     25005     32341
10  2022    16 2022-04-24      28387     39917     25005</code></pre>
</div>
</div>
<p>At this point, we have two plausible prediction rules. Looking at the predicted values alone does not tell us which rule performs better. To compare them, we need to measure how far each prediction is from the attendance that actually occurred.</p>
</section>
</section>
<section id="evaluating-predictions-during-model-development" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="evaluating-predictions-during-model-development"><span class="header-section-number">10.6</span> Evaluating Predictions During Model Development</h2>
<section id="predictions-are-not-enough" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predictions-are-not-enough">Predictions Are Not Enough</h3>
<p>We now have two ways to predict attendance: use the previous home game or use the home game two games earlier. Looking at the predicted values alone does not tell us which rule works better. We need to compare each prediction with the attendance that actually occurred.</p>
<p>For game (t), define the prediction error as:</p>
<p><span class="math display">\[
e_t = A_t - \widehat{A}_t
\]</span></p>
<p>where (A_t) is actual attendance and (_t) is predicted attendance. A positive error means the prediction was too low, while a negative error means it was too high. An error of zero would be a perfect prediction.</p>
<p>We can inspect a few errors from our two lagged prediction rules.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, gm, attendance, pred_lag1, pred_lag2) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(pred_lag1), <span class="sc">!</span><span class="fu">is.na</span>(pred_lag2)) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">error_lag1 =</span> attendance <span class="sc">-</span> pred_lag1,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">error_lag2 =</span> attendance <span class="sc">-</span> pred_lag2</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
    year    gm attendance pred_lag1 pred_lag2 error_lag1 error_lag2
   &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
 1  2022     3      32858     30369     35112       2489      -2254
 2  2022    10      26615     32858     30369      -6243      -3754
 3  2022    11      26568     26615     32858        -47      -6290
 4  2022    12      26167     26568     26615       -401       -448
 5  2022    13      32341     26167     26568       6174       5773
 6  2022    14      25005     32341     26167      -7336      -1162
 7  2022    15      39917     25005     32341      14912       7576
 8  2022    16      28387     39917     25005     -11530       3382
 9  2022    23      34206     28387     39917       5819      -5711
10  2022    24      36755     34206     28387       2549       8368</code></pre>
</div>
</div>
<p>Individual errors are useful, but we need a summary measure to compare prediction rules across many games. Different measures answer slightly different questions, so we will use three.</p>
<p>The <strong>Mean Absolute Error (MAE)</strong> measures the average size of the prediction errors, ignoring whether the prediction was too high or too low:</p>
<p><span class="math display">\[
\mathrm{MAE}
=
\frac{1}{T}
\sum_{t=1}^{T}
|e_t|
\]</span></p>
<p>Because MAE is measured in the same units as attendance, it has a direct interpretation. An MAE of 2,000 means that predictions miss actual attendance by 2,000 people on average.</p>
<p>The <strong>Root Mean Squared Error (RMSE)</strong> gives more weight to large prediction errors:</p>
<p><span class="math display">\[
\mathrm{RMSE}
=
\sqrt{
\frac{1}{T}
\sum_{t=1}^{T}
e_t^2
}
\]</span></p>
<p>RMSE is also measured in people. Compared with MAE, it increases more when a prediction rule makes a few large mistakes.</p>
<p>The <strong>Mean Absolute Percentage Error (MAPE)</strong> measures the size of each error relative to actual attendance:</p>
<p><span class="math display">\[
\mathrm{MAPE}
=
\frac{100}{T}
\sum_{t=1}^{T}
\left|
\frac{e_t}{A_t}
\right|
\]</span></p>
<p>MAPE expresses prediction errors as percentages. This can make performance easier to compare across outcomes measured on different scales. In our attendance data, actual attendance is always well above zero, so the denominator does not create a problem.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Training Performance Is Not Final Test Performance
</div>
</div>
<div class="callout-body-container callout-body">
<p>We are calculating these metrics using the training data because they help us develop and compare candidate prediction rules. They do not tell us how well the rules will perform on the 2025 test data.</p>
<p>We will use the test data only after we have finished developing our candidate rules.</p>
</div>
</div>
</section>
<section id="comparing-lag-1-and-lag-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="comparing-lag-1-and-lag-2">Comparing Lag 1 and Lag 2</h3>
<p>For a fair comparison, both rules should be evaluated on the same games. Because lag 2 has no prediction for the first two home games of each season, we keep only games for which both lagged predictions are available.</p>
<p>We first reshape the two prediction columns into a format where each row contains one actual attendance value and one prediction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>training_predictions <span class="ot">&lt;-</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(pred_lag1),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(pred_lag2)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(attendance, pred_lag1, pred_lag2) <span class="sc">|&gt;</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"pred_"</span>),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"model"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">".pred"</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(training_predictions)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  attendance model     .pred
       &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
1      32858 pred_lag1 30369
2      32858 pred_lag2 35112
3      26615 pred_lag1 32858
4      26615 pred_lag2 30369
5      26568 pred_lag1 26615
6      26568 pred_lag2 32858</code></pre>
</div>
</div>
<p>We can now use functions from <code>yardstick</code> to calculate MAE, RMSE, and MAPE for each rule.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>training_metrics <span class="ot">&lt;-</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  training_predictions <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mae =</span> <span class="fu">mae_vec</span>(attendance, .pred),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rmse =</span> <span class="fu">rmse_vec</span>(attendance, .pred),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mape =</span> <span class="fu">mape_vec</span>(attendance, .pred)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>training_metrics</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  model       mae  rmse  mape
  &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 pred_lag1 3209. 4183.  9.60
2 pred_lag2 3955. 5068. 11.8 </code></pre>
</div>
</div>
<p>For all three metrics, lower values indicate predictions that are closer to the actual attendance. Lag 1 performs better on all three metrics. Its MAE is about 3,209 fans, compared with 3,955 for lag 2, so using the previous home game reduces the typical prediction error by about 750 fans, or 19%. Lag 1 also has a lower RMSE (4,183 versus 5,068) and MAPE (9.6% versus 11.8%). Within the training data, attendance at the most recent home game therefore provides a better prediction than attendance two home games earlier.</p>
<p>Now that we have a way to compare candidate prediction rules, we can ask whether other ways of using historical attendance produce better predictions.</p>
</section>
</section>
<section id="combining-recent-information" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="combining-recent-information"><span class="header-section-number">10.7</span> Combining Recent Information</h2>
<section id="a-two-game-trailing-mean" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="a-two-game-trailing-mean">A Two-Game Trailing Mean</h3>
<p>So far, each prediction has used attendance from a single earlier home game. We can also combine information from several recent games into one prediction. One simple approach is to average attendance from the previous two home games.</p>
<p>For game (t), the two-game trailing mean is:</p>
<p><span class="math display">\[
\widehat{A}_t
=
\frac{A_{t-1} + A_{t-2}}{2}
\]</span></p>
<p>This rule gives equal weight to the previous two home games. If those games drew 32,000 and 36,000 people, the prediction for the next home game would be 34,000.</p>
<p>We construct this prediction within each season:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="ot">&lt;-</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year, gm) <span class="sc">|&gt;</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_trailing2 =</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">lag</span>(attendance, <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">lag</span>(attendance, <span class="dv">2</span>)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>cubs_train <span class="sc">|&gt;</span> </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gm, date, attendance, pred_trailing2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 243 × 4
      gm date       attendance pred_trailing2
   &lt;dbl&gt; &lt;date&gt;          &lt;dbl&gt;          &lt;dbl&gt;
 1     1 2022-04-07      35112            NA 
 2     2 2022-04-09      30369            NA 
 3     3 2022-04-10      32858         32740.
 4    10 2022-04-18      26615         31614.
 5    11 2022-04-19      26568         29736.
 6    12 2022-04-20      26167         26592.
 7    13 2022-04-21      32341         26368.
 8    14 2022-04-22      25005         29254 
 9    15 2022-04-23      39917         28673 
10    16 2022-04-24      28387         32461 
# ℹ 233 more rows</code></pre>
</div>
</div>
<p>The first two home games of each season have no <code>pred_trailing2</code> value because the rule requires attendance from two earlier home games.</p>
</section>
<section id="comparing-recent-history-prediction-rules" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="comparing-recent-history-prediction-rules">Comparing Recent-History Prediction Rules</h3>
<p>We now have three ways to use recent attendance:</p>
<ul>
<li><code>pred_lag1</code> uses the previous home game;</li>
<li><code>pred_lag2</code> uses the home game two games earlier;</li>
<li><code>pred_trailing2</code> averages the previous two home games.</li>
</ul>
<p>The third rule introduces a new idea: a prediction can combine information from multiple historical observations rather than rely on a single one.</p>
<p>To compare the three rules fairly, we evaluate them on the same games. Since both <code>pred_lag2</code> and <code>pred_trailing2</code> are unavailable for the first two home games of each season, we keep only games for which all three predictions are available.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>recent_history_predictions <span class="ot">&lt;-</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(pred_lag1),</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(pred_lag2),</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(pred_trailing2)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    attendance,</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    pred_lag1,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    pred_lag2,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    pred_trailing2</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"pred_"</span>),</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"model"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">".pred"</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then calculate the same three error metrics as before.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>recent_history_metrics <span class="ot">&lt;-</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  recent_history_predictions <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mae =</span> <span class="fu">mae_vec</span>(attendance, .pred),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rmse =</span> <span class="fu">rmse_vec</span>(attendance, .pred),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mape =</span> <span class="fu">mape_vec</span>(attendance, .pred)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>recent_history_metrics</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  model            mae  rmse  mape
  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 pred_lag1      3209. 4183.  9.60
2 pred_lag2      3955. 5068. 11.8 
3 pred_trailing2 3214. 4123.  9.58</code></pre>
</div>
</div>
<p>The two-game trailing mean performs almost identically to lag 1 on MAE and MAPE, but has a slightly lower RMSE. This suggests that combining multiple recent games can be useful because it makes the prediction less sensitive to any one unusually high or low attendance outcome. At the same time, the gains are modest: using more historical observations does not automatically improve prediction.</p>
</section>
</section>
<section id="using-more-relevant-historical-games" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="using-more-relevant-historical-games"><span class="header-section-number">10.8</span> Using More Relevant Historical Games</h2>
<section id="predicting-attendance-by-opponent" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="predicting-attendance-by-opponent">Predicting Attendance by Opponent</h3>
<p>So far, we have chosen historical games because they happened recently. Another possibility is to use past games that are similar to the game we want to predict. One feature we know before a game is the opposing team.</p>
<p>Suppose we want to predict attendance for a 2024 home game against Milwaukee. Rather than use attendance from the most recent Cubs home game, we could look at Cubs home games against Milwaukee in 2023 and use their average attendance. The prediction rule is then: <strong>for each opponent, predict attendance using the average attendance from games against that opponent in the previous season</strong>.</p>
<p>We can first construct these opponent averages for 2023.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>opp_means_2023 <span class="ot">&lt;-</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2023</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(opp) <span class="sc">|&gt;</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_opp_1yr =</span> <span class="fu">mean</span>(attendance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We then attach the appropriate opponent average to each 2024 game.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>opp_predictions_2024 <span class="ot">&lt;-</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2024</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    opp_means_2023,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"opp"</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Games against the same opponent receive the same prediction because the rule uses the same historical group to predict each of them. If an opponent did not appear in the historical data used by the rule, the prediction will be <code>NA</code>.</p>
</section>
<section id="reusing-the-same-prediction-logic" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="reusing-the-same-prediction-logic">Reusing the Same Prediction Logic</h3>
<p>We may also want to use more than one previous season. For example, we could predict 2024 attendance using average attendance against each opponent across both 2022 and 2023. The steps are almost identical: choose the historical years, calculate an average for each opponent, and join those averages to the games we want to predict.</p>
<p>When the same analytical steps need to be repeated with different inputs, a function can help us avoid rewriting the same code. The function below takes three inputs: the data, the year we want to predict, and the number of previous years to use.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>predict_by_opponent <span class="ot">&lt;-</span> <span class="cf">function</span>(data, target_year, years_back) {</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  opponent_means <span class="ot">&lt;-</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    data <span class="sc">|&gt;</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>      year <span class="sc">&gt;=</span> target_year <span class="sc">-</span> years_back,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>      year <span class="sc">&lt;</span> target_year</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(opp) <span class="sc">|&gt;</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">.pred =</span> <span class="fu">mean</span>(attendance, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  data <span class="sc">|&gt;</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> target_year) <span class="sc">|&gt;</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">left_join</span>(</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>      opponent_means,</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">by =</span> <span class="st">"opp"</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The function does the same two things we did manually above. First, it calculates average attendance by opponent over the requested historical window. Second, it joins those averages to the games in the target year.</p>
<p>We can now create a one-year and a two-year opponent prediction for 2024 by changing only <code>years_back</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>opp_1yr_2024 <span class="ot">&lt;-</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict_by_opponent</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> cubs_train,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">target_year =</span> <span class="dv">2024</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">years_back =</span> <span class="dv">1</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pred_opp_1yr =</span> .pred)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>opp_2yr_2024 <span class="ot">&lt;-</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict_by_opponent</span>(</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> cubs_train,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">target_year =</span> <span class="dv">2024</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">years_back =</span> <span class="dv">2</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pred_opp_2yr =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The one-year rule uses only 2023 games to predict 2024. The two-year rule uses games from 2022 and 2023. Combining two seasons gives each opponent mean more historical observations, which may make the prediction less sensitive to an unusual game. The trade-off is that some of those observations are older and may be less representative of current attendance.</p>
<div class="exercise">
<div class="exercise-time">
<p>5 min</p>
</div>
<p>Consider the two opponent-based prediction rules.</p>
<ol type="1">
<li>What historical games are used when <code>target_year = 2024</code> and <code>years_back = 1</code>?</li>
<li>What changes when <code>years_back = 2</code>?</li>
<li>Why might using two years produce a more stable prediction?</li>
<li>Why might using older games make the prediction less useful?</li>
</ol>
</div>
</section>
</section>
<section id="comparing-candidate-prediction-rules" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="comparing-candidate-prediction-rules"><span class="header-section-number">10.9</span> Comparing Candidate Prediction Rules</h2>
<section id="evaluating-the-rules-on-the-training-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="evaluating-the-rules-on-the-training-data">Evaluating the Rules on the Training Data</h3>
<p>We now have five candidate prediction rules. Three use recent attendance (<code>pred_lag1</code>, <code>pred_lag2</code>, and <code>pred_trailing2</code>), while two use average attendance against the same opponent (<code>pred_opp_1yr</code> and <code>pred_opp_2yr</code>).</p>
<p>Before moving to the 2025 test data, we compare all five rules on 2024 games. We use 2024 because every rule can be constructed using information from earlier games or earlier seasons. This lets us compare the rules on a common year while still treating the exercise as part of model development.</p>
<p>We already created each prediction in the previous sections, so we do not need to run the models again. We can bring the predictions together in one data frame.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>candidate_predictions_2024 <span class="ot">&lt;-</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  cubs_train <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2024</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    year,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    gm,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    date,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    opp,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    attendance,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    pred_lag1,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    pred_lag2,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    pred_trailing2</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    opp_1yr_2024 <span class="sc">|&gt;</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, gm, pred_opp_1yr),</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"gm"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>    opp_2yr_2024 <span class="sc">|&gt;</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, gm, pred_opp_2yr),</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"gm"</span>)</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>For a fair comparison, every rule should be evaluated on the same games. We therefore keep only games for which all five predictions are available, then reshape the data so that each row contains one actual attendance value and one prediction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>candidate_predictions_long <span class="ot">&lt;-</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  candidate_predictions_2024 <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(<span class="fu">starts_with</span>(<span class="st">"pred_"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"pred_"</span>),</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"model"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">".pred"</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can now calculate MAE, RMSE, and MAPE for each rule using the same workflow as before.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>candidate_metrics <span class="ot">&lt;-</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  candidate_predictions_long <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mae =</span> <span class="fu">mae_vec</span>(attendance, .pred),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rmse =</span> <span class="fu">rmse_vec</span>(attendance, .pred),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">mape =</span> <span class="fu">mape_vec</span>(attendance, .pred)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>candidate_metrics</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  model            mae  rmse  mape
  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 pred_lag1      2909. 3916.  8.24
2 pred_lag2      3375. 4697.  9.61
3 pred_opp_1yr   3745. 4477. 10.3 
4 pred_opp_2yr   4263. 4964. 11.5 
5 pred_trailing2 2669. 3774.  7.57</code></pre>
</div>
</div>
<p>On the 2024 training data, the two-game trailing mean performs best overall. It has the lowest MAE (2,669), RMSE (3,774), and MAPE (7.57%). Lag 1 is the next-best rule, while lag 2 performs worse on all three metrics. The opponent-based rules perform worse than the recent-history rules, and using two years of opponent history performs worse than using only the previous year. In this training sample, then, recent attendance appears more useful than opponent-specific history. These results help us identify promising rules, but they are still based on the data used during model development.</p>
</section>
</section>
<section id="evaluating-predictions-on-unseen-data" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="evaluating-predictions-on-unseen-data"><span class="header-section-number">10.10</span> Evaluating Predictions on Unseen Data</h2>
<section id="moving-from-training-to-test-data" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="moving-from-training-to-test-data">Moving from Training to Test Data</h3>
<p>So far, we used the training data to compare the candidate rules and learn which ones looked promising, so strong performance on those same games may not carry over to a new season. The 2025 test data give us a fresh comparison. These games played no role in developing or selecting the candidate rules. We can therefore use them to ask whether the patterns that looked useful during training also produce accurate predictions for new games.</p>
</section>
<section id="applying-the-recent-history-rules-to-2025" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="applying-the-recent-history-rules-to-2025">Applying the Recent-History Rules to 2025</h3>
<p>For the lag-based rules, earlier 2025 games can be used to predict later 2025 games. Once a game has occurred, its attendance is known and is therefore available when predicting the next game. What we cannot use is attendance from the game being predicted or from any game that takes place later.</p>
<p>We apply the same three recent-history rules to the 2025 games.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>cubs_test_predictions <span class="ot">&lt;-</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  cubs_test <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(gm) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_lag1 =</span> <span class="fu">lag</span>(attendance, <span class="dv">1</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_lag2 =</span> <span class="fu">lag</span>(attendance, <span class="dv">2</span>),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred_trailing2 =</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>      (<span class="fu">lag</span>(attendance, <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">lag</span>(attendance, <span class="dv">2</span>)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As before, the first game has no lag-1 prediction, while the first two games have no lag-2 or trailing-2 prediction.</p>
</section>
<section id="applying-the-opponent-rules-to-2025" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="applying-the-opponent-rules-to-2025">Applying the Opponent Rules to 2025</h3>
<p>The opponent-based rules use historical averages calculated from seasons before the year being predicted. We use the function from the previous section to create one-year and two-year opponent predictions for 2025.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>opp_1yr_2025 <span class="ot">&lt;-</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict_by_opponent</span>(</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> cubs_attendance,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">target_year =</span> <span class="dv">2025</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">years_back =</span> <span class="dv">1</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pred_opp_1yr =</span> .pred)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>opp_2yr_2025 <span class="ot">&lt;-</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict_by_opponent</span>(</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> cubs_attendance,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">target_year =</span> <span class="dv">2025</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">years_back =</span> <span class="dv">2</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">pred_opp_2yr =</span> .pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The one-year rule uses 2024 attendance against each opponent. The two-year rule uses 2023 and 2024. Unlike the lagged rules, these opponent averages are not updated using 2025 attendance.</p>
<p>We now bring all five predictions together.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>test_predictions_2025 <span class="ot">&lt;-</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  cubs_test_predictions <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    opp_1yr_2025 <span class="sc">|&gt;</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, gm, pred_opp_1yr),</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"gm"</span>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    opp_2yr_2025 <span class="sc">|&gt;</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(year, gm, pred_opp_2yr),</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"gm"</span>)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="comparing-test-set-performance" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="comparing-test-set-performance">Comparing Test-Set Performance</h3>
<p>For a fair comparison, we again evaluate every rule on the same games. We keep only games for which all five predictions are available, reshape the predictions into long format, and calculate the same three error metrics.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>test_predictions_long <span class="ot">&lt;-</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  test_predictions_2025 <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(<span class="fu">starts_with</span>(<span class="st">"pred_"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"pred_"</span>),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"model"</span>,</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">".pred"</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>test_metrics <span class="ot">&lt;-</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  test_predictions_long <span class="sc">|&gt;</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">mae =</span> <span class="fu">mae_vec</span>(attendance, .pred),</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">rmse =</span> <span class="fu">rmse_vec</span>(attendance, .pred),</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">mape =</span> <span class="fu">mape_vec</span>(attendance, .pred)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>test_metrics</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  model            mae  rmse  mape
  &lt;chr&gt;          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 pred_lag1      2681. 3863.  7.43
2 pred_lag2      3383. 4446.  9.46
3 pred_opp_1yr   2806. 3565.  7.67
4 pred_opp_2yr   3059. 3763.  8.21
5 pred_trailing2 2767. 3687.  7.70</code></pre>
</div>
</div>
</section>
<section id="which-prediction-rule-is-best" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="which-prediction-rule-is-best">Which Prediction Rule Is Best?</h3>
<p>There is no single prediction rule that performs best on every metric. Lag 1 has the lowest MAE (2,681) and MAPE (7.43%), while the one-year opponent model has the lowest RMSE (3,565). The two-game trailing mean is also competitive, but it is no longer the best-performing rule on the test data.</p>
<p>Which result matters most depends on the business decision. In our setting, MAE is a natural primary measure because it tells us the typical prediction error in number of attendees — the same quantity that drives staffing and supply decisions. By that measure, lag 1 performs best: its predictions miss actual attendance by about 2,681 people on average.</p>
<p>RMSE is also useful because it places more weight on unusually large prediction errors. If large mistakes are especially costly — for example, because severe understaffing creates long queues or shortages — the one-year opponent model may be more attractive because it has the lowest RMSE. MAPE gives a useful percentage interpretation, but adds less here because attendance is measured on a similar scale across games.</p>
<p>The test results also change what we learned during model development. On the 2024 training data, the two-game trailing mean performed best on all three metrics. In 2025, the ranking depends on how prediction error is measured. This is why we needed the test data: the patterns that look strongest during model development do not always remain strongest when applied to new observations.</p>
</section>
</section>
<section id="summary" class="level2" data-number="10.11">
<h2 data-number="10.11" class="anchored" data-anchor-id="summary"><span class="header-section-number">10.11</span> Summary</h2>
<p>In this chapter, we treated stadium attendance as a prediction problem. We used historical games to construct several prediction rules, including lags, an average of recent games, and averages based on the opposing team. We compared those rules during model development and then evaluated them on a later season that played no role in choosing them.</p>
<p>The results highlighted several lessons. Recent information can be useful, but combining more observations does not automatically improve prediction. Historical observations can also be selected because they are similar to the case we want to predict, not just because they are recent. Training performance helps us compare candidate rules, but test performance tells us whether those patterns continue to hold for new observations. We also saw that there may be no single best rule across every error metric, so the choice of metric should reflect the business decision the prediction will support.</p>
<p>The specific prediction rules in this chapter are simple, but the logic is general. In later courses or applications, you may encounter methods that combine many variables and capture patterns that cannot be summarized well by a few lags, averages, or group means. The machinery may become more complicated, but the core workflow remains the same: define the outcome, use only information available when the prediction is made, develop candidate rules using historical data, and evaluate them on observations that played no role in choosing those rules.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../advanced_analytics/causal_analytics.html" class="pagination-link" aria-label="Causal Analytics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Causal Analytics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../data_management/data_storage.html" class="pagination-link" aria-label="Storing and Using Existing Data">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Storing and Using Existing Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>